### ISSUE TITLE
Chapter Request: Boston

### ISSUE THREAD

**Issue by RichardLitt** [papers-we-love/organizers#1]
> Have a chapter repository created within the Papers We Love organization: Open an issue on this repo requesting a chapter repo and telling us about yourself, who is helping you out, where we can find you online (twitter, etc) and where you're planning on starting the chapter. One of the Papers We Love administrators will get in touch with you and once everything is squared away will create the repo for your planned chapter. You will be added to a chapter-organizers team and given read / write access to the repo.

**Where**: Boston & Cambridge
**Who**: 
 * [Richard Littauer](https://github.com/RichardLitt), [@richlitt](https://twitter.com/richlitt), MIT Media Lab and IPFS.io. 
 * [Elena Glassman](https://github.com/eglassman), [@roboticwrestler](https://twitter.com/roboticwrestler), MIT CSAIL

Existing management repository that can be moved and renamed: [RichardLitt/papers-we-love-bos](https://github.com/RichardLitt/papers-we-love-bos).

**Comment by DarrenN** [comment]
@RichardLitt do you have an GitHub username for Elena?

**Comment by DarrenN** [comment]
Repo created: https://github.com/papers-we-love/boston

**Comment by RichardLitt** [comment]
Nice! Thank you! Alright, going to transfer over things from previous repo, work on getting a meeting setup sooner. I'll provide feedback on how this can be streamlined for others as I go.

**Comment by DarrenN** [comment]
:+1:

**Comment by RichardLitt** [comment]
Oh, and Elena's GitHub name was linked above: https://github.com/eglassman
