### ISSUE TITLE
Portland

### ISSUE THREAD

**Issue by carllerche** [papers-we-love/organizers#11]
Hi all,

I'm interested in getting a chapter going in Portland, OR. I'm in the very early stages of the process. I'll be updating this ticket as things evolve and the issue comments could be used to organize getting this going.

**About me**: A dev in Portland :) You can find me on twitter at https://twitter.com/carllerche.

**People helping**: TBD. Still working on this.

**Comment by jden** [comment]
Also very interested, and would love to help out. I'm going to be Portland-based in the next month or so.

**Comment by jden** [comment]
I made a #pwlpdx channel in pwl slack, come /join us if you're interested :)

**Comment by DarrenN** [comment]
@carllerche okay, will set you up. Are we adding @jden as an organizer as well?

**Comment by DarrenN** [comment]
@carllerche Portland is setup - https://github.com/papers-we-love/portland

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

**Comment by kpfell** [comment]
Hi, @jden and @carllerche! 

My coworker at Simple and I have been figuring out when and where we could feasibly host PWL stuff over the past couple of months, so we'd already have a venue and maybe food/sponsors already set up? We wanted to go find some speakers next, so I tweeted [this thing](https://twitter.com/kf/status/724356748266500096) just today.

Would be down to team up, if you are!
