### ISSUE TITLE
Utrecht, NL

### ISSUE THREAD

**Issue by aochagavia** [papers-we-love/organizers#12]
Where: Utrecht, The Netherlands

Who: @duijf, @arianvp and @aochagavia. We are undergraduate students at Universiteit Utrecht, involved in open source projects and eager to learn more. Two of us are going to begin the Computing Science master of the university in September.

Context: The developer community in Utrecht has grown a lot in the last years and there are many local meetups. We think the timing is perfect to begin with PWL in Utrecht.

**Comment by aochagavia** [comment]
cc @DarrenN

**Comment by DarrenN** [comment]
Hello @aochagavia - the three of you have been invited to the Chapter Organizers team which will give you access to https://github.com/papers-we-love/utrecht

Please update the README and the Code of Conduct for your chapter.

**Comment by aochagavia** [comment]
Awesome! Thanks!
