### ISSUE TITLE
Chattanooga

### ISSUE THREAD

**Issue by NeilMenne** [papers-we-love/organizers#13]
**Where**: Chattanooga
**Who**:
1. [Neil Menne](https://github.com/NeilMenne) and on twitter [@the1evilgenius](https://twitter.com/the1evilgenius)
2. [Noel Weichbrodt](https://github.com/noelweichbrodt) and on twitter [@noelweichbrodt](https://twitter.com/noelweichbrodt)

Announcement of PWL tomorrow w/ [Meetup](http://www.meetup.com/Papers-We-Love-Chattanooga/) already ready to go.

Particular papers are being chosen this evening and tomorrow.

**Comment by DarrenN** [comment]
@NeilMenne - the repo is setup https://github.com/papers-we-love/chattanooga

You and @noelweichbrodt have been added as organizers.

Once you've accepted the invitation, please update the README and Code of Conduct within your repo. Once you've had your first meetup let us know and we'll start the process to add you to the chapter listings.

Thanks!
