### ISSUE TITLE
San Diego

### ISSUE THREAD

**Issue by chrishiestand** [papers-we-love/organizers#16]
I'm a software engineer with a linux sysadmin background in San Diego. I've more recently worked with new distributed systems and really started enjoying understand the theory behind this amazing new tech (often based on old papers). I don't have any co-organizers or a meeting space yet, but I imagine that will come along in time. It would help to first start a meetup and see how much demand there is.

**Comment by DarrenN** [comment]
Hi @chrishiestand - do you have a general idea on when you would hold a meetup, or have you been able to get any additional interest in the San Diego area?

**Comment by chrishiestand** [comment]
@DarrenN I was thinking once a month on a Tuesday or Thursday evening. I haven't advertised yet because I wanted to get permission from you to use the name "Papers We Love". Can I create a meetup with the name to start gathering interest?

**Comment by zeeshanlakhani** [comment]
@chrishiestand yes you can, just check for the things mentioned in https://github.com/papers-we-love/organizers/blob/master/README.md, and ping us w/ questions on slack or here.

**Comment by carlisia** [comment]
Hey @chrishiestand, I am very interested in helping establish a PWL chapter in SD. Are you on the PWL slack?

**Comment by chrishiestand** [comment]
@carlisia yes indeed, I'm @chrishiestand there too. You help organize the SD Gophers right? The more the merrier, see you on slack.

**Comment by DarrenN** [comment]
Hi @chrishiestand - your repo is all setup https://github.com/papers-we-love/san-diego

Please update the README and the Code of Conduct with your local information.

Thanks!

**Comment by chrishiestand** [comment]
@DarrenN Thank you very much!
