### ISSUE TITLE
Remote

### ISSUE THREAD

**Issue by knewter** [papers-we-love/organizers#17]
I'm the CTO of [DailyDrip](http://www.dailydrip.com) located in Birmingham, AL.  Even though it's a 'major' metro, Birmingham does not have a critical mass of software developers interested in socializing / meetups.  I run one of the biggest local meetups (Birmingham Open Source Software), but even still we have maybe 20 people at tops at a given meeting.

Due to my experience with this and my desire to interact with other experienced software developers more frequently, I wrote up [why and how we were organizing a Remote Meetup for Elm](https://www.dailydrip.com/blog/organizing-a-remote-meetup-for-elm).  @franzejr from [RemoteMeetup](http://remotemeetup.com/) got in touch with me before our first Elm meetup had happened, and we teamed up to help make Remote Meetups more awesome.  As a consequence, we had 100 people registered and 83 on the waitlist for [the first ever Elm Remote Meetup](https://www.dailydrip.com/topics/elm-remote-meetup/drips/elm-remote-meetup-1).  We've since solved the 'only 100 can attend' problem.  We also run these quite a bit (@franzejr moreso than me) and have pretty good processes in place for making them successful.  There were some technical difficulties with the first one, but even still it was very successful, and we've got the BigMarker CEO working with us directly to help reduce pain points in the future.

That's...a lot of starter context.  Moving on.

I recently got extremely interested in papers again generally, and thought it would be great to run a remote PapersWeLove.  I reached out to @cmeiklejohn and asked if he would help me co-organize one (as he's also a bit more remote than he once was), and he agreed.  Consequently, the co-organizers are as follows:

- @knewter
- @cmeiklejohn
- @franzejr

We would love to have a remote chapter repository opened up, at which point we'll go ahead and organize the first meetup (which @cmeiklejohn has agreed to speak at to kick off).

Thanks in advance! (and if you read all that, niiiiice)

**Comment by hakutsuru** [comment]
Thank you for providing starter context.

I have had a brief chat with PWL.org leadership, and expect to set up this chapter repository for you.

But we want to discuss remote chapters a bit first. With due respect to YAGNI, I suspect your remote meetup will be successful. If so, then we may need to help similar chapters organize by language, region or subregion.

Your thoughts on this would be welcome. I hope to get our PWL.org discussion started this weekend, so that we can fulfill this request soon.

**Comment by knewter** [comment]
@hakutsuru took me a bit to get back to my github notifications...

I, too, expect this to be successful, and we'll make sure there's an easy to follow framework for setting up more granular chapters.  I'm starting my second large remote meetup for Elixir now, and it was way easier to get started as I already have a process in place.  There's a basic community organization template that I use to start the thing off and agree on day-of-month and time, and then it basically gets used in the future to help organize speakers.  The Elixir one is here: https://docs.google.com/document/d/10SdN_V3-7IvDZQINNIO6QRou_6hj69dlkINGjtRPjjk/edit#heading=h.rbry1j7i28bz

Anyway, I expect to ultimately collect all the collateral material into a guidebook for running remote meetups, as I want to help there be more of them in the world.  I presume @franzejr from RemoteMeetup.com will assist me in this as it will be useful for all of their meetups as well!

Let me know if you need anything else from me to get the chapter started.

**Comment by hakutsuru** [comment]
@knewter: We have been busy with pwlconf, but I hope to get this done by the weekend. Will let you know if we need anything. Thanks.

**Comment by carlisia** [comment]
Hey @knewter I too am very interested in this. I help run the Go Remote Meetup umbrella of @franzejr's org, and am also trying to help establish a PWL chapter in San Diego, where I live. 

Having a remote PWL chapter would also be great. We have been having great success with the BigMarker tool, so this should be very doable.

**Comment by zeeshanlakhani** [comment]
@hakutsuru mind getting on this?

**Comment by hakutsuru** [comment]
Getting this done is near the top of my list, sorry for the delay. If not tonight, then over the weekend.

**Comment by carlisia** [comment]
Let me know if there's interest in using BigMarker and I can help seek sponsorship. Both the Go and the Main Remote meetup accounts got sponsorships and we have the ability to host up to 1,000 attendee.

**Comment by knewter** [comment]
We have the bigmarker sponsorship already in place.

**Comment by carlisia** [comment]
Do you have the account already setup? I'd like to join.

**Comment by franzejr** [comment]
I think Josh is saying we are going to use the Main Remote Meetup account ?

Franzé Jr

**Comment by carlisia** [comment]
Oh. That's a bummer. I am exclusively interested in papers and getting notifications for all the meetups in that account would probably make me not want to sign up.  @knewter what is the rational for not having a separate account only for pwl and seek out a sponsorship for that? It really would not be difficult to get.

**Comment by franzejr** [comment]
Yeah, you are right, @carlisia. I just talked with Zhu-Song, Bigmarker CEO, he can provide us another channel just for Papers We Love :)

**Comment by carlisia** [comment]
Woohooo!!! @franzejr you are so dah 💣!

**Comment by hakutsuru** [comment]
@knewter - your repo is setup https://github.com/papers-we-love/remote-pwl

I am open to changing the name -- the thinking here is that pwl in the repo name will make a reader curious (since pwl is unlikely to be part of a city name). The remote-pwl readme should explain its unique remote nature.

You and your team should have invitations to join the chapter-organizers team (knewter, cmeiklejohn and franzejr). Please update the README and the Code of Conduct within your repo.

Thanks for your help making this happen.

**Comment by hakutsuru** [comment]
@DarrenN, @zeeshanlakhani: Closing this per policy, let me know if there was anything about the process that could be improved via our private channels.

**Comment by zhusongmei** [comment]
@carlisia sorry for the late response. if you register on BigMarker and create a channel, then send me the link to it and we can make the adjustments.
