### ISSUE TITLE
Austin, TX

### ISSUE THREAD

**Issue by pfraze** [papers-we-love/organizers#18]
We've got a fledgling meetup in ATX. We've held 2 events already. Attendance is still low, but we're working on ways to improve it (looking for interest in UT, announcing at other meetups, and moving downtown).

I'm Paul Frazee, I've lived in ATX for 5 years and I was a core part of the Distributed Systems Enthusiasts meetup in ATX, during its 2 year run. Twitter: https://twitter.com/pfrazee

Sukant Sharja (https://twitter.com/shajra) is my co-organizer. Other than being a solid member of the group, he's helped with getting a space for the meetups, and acts as my backup if there's ever a month I can't attend.

**Comment by DarrenN** [comment]
@pfraze - your repo is setup https://github.com/papers-we-love/austin

You should have an invitation to join the chapter-organizers team. Please update the README and the Code of Conduct within your repo.

Does Sukant have a GitHub user name?

Thanks!

**Comment by pfraze** [comment]
Good deal!

I'll get back to you on Sukant's username

**Comment by pfraze** [comment]
It's https://github.com/shajra

**Comment by DarrenN** [comment]
Invitate to @shajra sent
