### ISSUE TITLE
Seattle

### ISSUE THREAD

**Issue by fernomac** [papers-we-love/organizers#19]
Hi! The Seattle PWL chapter isn't precisely new, and we're already on the list of official chapters, but we haven't yet gotten around to setting up a github repo. I'm finally doing so!

Primary organizers are @ankurcha and myself.

Thanks!

cc @mechazoidal

**Comment by DarrenN** [comment]
Howdy, your repo is all setup: https://github.com/papers-we-love/seattle

You and @ankurcha should have received invites to join the org

Please update the README and Code of Conduct with your local information.

Thanks!

**Comment by fernomac** [comment]
Thanks @DarrenN!
