### ISSUE TITLE
Washington, DC

### ISSUE THREAD

**Issue by leesharma** [papers-we-love/organizers#20]
> Have a chapter repository created within the Papers We Love organization: Open an issue on this repo requesting a chapter repo and telling us about yourself, who is helping you out, where we can find you online (twitter, etc) and where you're planning on starting the chapter. One of the Papers We Love administrators will get in touch with you and once everything is squared away will create the repo for your planned chapter. You will be added to a chapter-organizers team and given read / write access to the repo.

**Chapter details:**

This chapter is meant to serve the Washington DC area; specifically, we're aiming to meet in Northern VA near a metro station. We're set to start meeting at [CustomInk][customink] in Fairfax, VA ([map][customink-map]) later this month.

[Here is a link to our first meetup][first-meetup], which will be on Wednesday, August 24th, and we're planning on holding meetings monthly thereafter. Over the first few meetings, we hope to try a few different formats and then settle into something that works for the community.

**Find us online:**
- meetup: [Papers We Love DC/NoVA][meetup]
- twitter: [@paperswelovedc][twitter]
- slack channel: #paperswelove on DCTech slack

**Organizers:**
- Lee Sharma (gh: @leesharma, t: [@theleesharma][t-theleesharma])
- Howard Miller (gh: @h-m-m, t: [@hmmiller][t-hmmiller])

[t-theleesharma]: https://twitter.com/theleesharma
[t-hmmiller]: https://twitter.com/hmmiller
[customink]: http://www.customink.com/
[customink-map]: https://goo.gl/maps/hFfcPzFFE3w
[first-meetup]: http://www.meetup.com/Papers-We-Love-DC-NoVA/events/232351004/
[meetup]: http://www.meetup.com/Papers-We-Love-DC-NoVA/
[twitter]: https://twitter.com/paperswelovedc

**Comment by DarrenN** [comment]
Howdy! Your repo has been setup - https://github.com/papers-we-love/washington-dc

You and @h-m-m have been invited to the organization.

Please update your README and Code of Conduct with local information.

Thanks!
