### ISSUE TITLE
Chapter Request: Budapest, Hungary

### ISSUE THREAD

**Issue by danimad** [papers-we-love/organizers#21]
Where: Budapest, Hungary.

Who: at first just me, @danimad.  I took over the organization of the Budapest Haskell User Group this year, and I thought it would be a good idea to start a local PwL as well.
I organized a couple of events, and a hackathon already, (so I already know a little bit, how this racket works:)), so I know places and companies where we could hold these events.
As I said I organize a Haskell meetup so I mostly know that crowd, but I want this to be all-inclusive, non language specific event, so I will talk to the other meetup's organizers, to ask if they want to help, or they know if some of their members would like to hold a presentation.

I almost certainly forgot to mention something, so if you have more questions just let me know!

**Comment by hakutsuru** [comment]
Team:

I created the budapest repo, invited chapter organizers to collaborate via github, and sent an update via email. 

If there is anything I could be doing to improve this process, let me know.

If no one has comments, I will close this issue later this week.

**Comment by hakutsuru** [comment]
@danimad Budapest is setup - https://github.com/papers-we-love/budapest

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

**Comment by danimad** [comment]
Thanks! I will fill read the info, and fill out the template files shortly.
