### ISSUE TITLE
Chapter Request: Brasilia, Brazil

### ISSUE THREAD

**Issue by alessandroleite** [papers-we-love/organizers#22]
Where: Brasilia, Brazil
Who: Alessandro Leite ([@alessandroleite](https://twitter.com/alessandroleite)) and Fabricio Buzeto ([@nukdf](https://twitter.com/nukdf)). We've already organized other events in Brazil.
Meetup: https://www.meetup.com/papers-we-love-bsb/

**Comment by hakutsuru** [comment]
@alessandroleite & @nuk Brasilia is setup - https://github.com/papers-we-love/brasilia

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

(Leaving this issue open for comments, but expect to close it next week.)

**Comment by alessandroleite** [comment]
Thanks @hakutsuru. I'm wait the invitation for the organizers team.

**Comment by hakutsuru** [comment]
You were already invited (on 2016 October 05). Maybe the GitHub invitation went to your spam folder?

**Comment by alessandroleite** [comment]
Could you please send me it again?

**Comment by hakutsuru** [comment]
Original invite canceled. A new invite has been sent.

**Comment by alessandroleite** [comment]
Thanks.

**Comment by alessandroleite** [comment]
Hello guys, 

Could you give me admin permission on this repository https://github.com/papers-we-love/brasilia? 
For instance, I would like to edit the topics of the repository.

**Comment by hakutsuru** [comment]
I changed permissions for @alessandroleite & @nuk to Admin.

**Comment by alessandroleite** [comment]
Thanks @hakutsuru 

We would love the set of pictures! Can you do it for us?
Currently, we are using Meetup and Twitter.

**Comment by hakutsuru** [comment]
> We would love the set of pictures! Can you do it for us?

Do you mean PWL/chapter logos?

We are busy preparing for *PWLConf*, but @DarrenN might be able to handle this soon.

**Comment by alessandroleite** [comment]
Yes. Thanks.

**Comment by DarrenN** [comment]
@alessandroleite will get some together for you. Might take a day or so.

**Comment by DarrenN** [comment]
@alessandroleite here you go https://www.dropbox.com/s/mexxo670cnt7ul3/pwl-brasilia.zip?dl=0

**Comment by alessandroleite** [comment]
Great! Thanks @DarrenN
