### ISSUE TITLE
Chapter Request: Kyiv, Ukraine

### ISSUE THREAD

**Issue by joymax** [papers-we-love/organizers#23]
Where: Kyiv, Ukraine

When: October 22th, 2016

Who: Roman Liutikov @roman01la and Maksym Klymyshyn @joymax. We've organizers of  a bunch of events in Ukraine like Kyiv JS, Pycon Ukraine and others. We think we're able to start PWL in Kyiv and it's important topic here because of #24 in [global services location index by kearney](http://www.prnewswire.com/news-releases/at-kearney-releases-2016-global-services-location-index-gsli-300201927.html) and a huge amount of software engineers out here.

**Comment by roman01la** [comment]
Here's event page https://roman01la.github.io/pwl-kyiv/
and repo https://github.com/roman01la/pwl-kyiv

**Comment by hakutsuru** [comment]
@joymax, @roman01la: Kyiv is setup - https://github.com/papers-we-love/kyiv

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by roman01la** [comment]
@hakutsuru Done. Thanks!
