### ISSUE TITLE
Chapter Request: Gothenburg, Sweden

### ISSUE THREAD

**Issue by nachivpn** [papers-we-love/organizers#25]
Hello,

I'm Nachi, a Masters student in Gothenburg. I study Computer Science (Algorithms, Languages and Logic) at Chalmers University. I've attended PWL meetups in Bangalore and had many good experiences. I would like to recreate the same in Gothenburg and there appears to be significant interest among the students and faculty too. We have a very active research community at Chalmers, and hence a large number of potential speakers.

Chalmers makes it very easy for students to book halls within the campus for meetups, so space isn't a problem.

My contact & details:
* twitter: [@NachiVpn](https://twitter.com/NachiVpn)
* [Home page](http://nachivpn.me/)

**Comment by hakutsuru** [comment]
@nachivpn: Welcome!

Will meetings be open to the public? If so, how will the chapter publicize meetings?

Papers-We-Love aims to facilitate collaboration between industry and academia, and to promote inclusive knowledge sharing. If the community would be limited to Chalmers University, that would probably be fine, but PWL would like to know why. Thanks.

**Comment by nachivpn** [comment]
Hey @hakutsuru 

Yes, the meetings will be open to public. 

Currently, we're relying on spreading the word through our [meetup group](https://www.meetup.com/Papers-We-Love-Gothenburg/) and our [twitter account](https://twitter.com/pwlgot).

Additionally, we created a channel ( #pwlgot ) at https://paperswelove.slack.com/

One of the primary reasons behind starting this chapter instead of continuing the practice of discussing papers in existing research groups is to facilitate collaboration between academia and industry. I come from an industrial background myself :)

**Comment by hakutsuru** [comment]
Thank you! I expect to have the repo created this weekend (which you should update with your chapter and organizer information.)

You already have a meetup scheduled. We should add the Gothenburg chapter to the main PWL site (paperswelove.org) after your first meeting (you should remind us).

If you have video, audio, slides or any other media from the event, we could share those with the larger community as well.

**Comment by nachivpn** [comment]
Will do!

**Comment by hakutsuru** [comment]
@nachivpn: Gothenburg is setup - https://github.com/papers-we-love/gothenburg

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

**Comment by nachivpn** [comment]
@hakutsuru - Thanks.

And done - I've updated the README and Code of conduct!
