### ISSUE TITLE
Chapter Request: St. Petersburg, Russia

### ISSUE THREAD

**Issue by andreypopp** [papers-we-love/organizers#26]
Hello,

@termina1 and me (@andreypopp) are going to kickstart a new chapter in St. Petersburg, Russia (the first one in Russian it seems). We will hold the first meeting this or the next week (waiting for the confirmation from the first our speaker with its own research to be presented).

Twitter contacts:
* [@PapersWeLoveSpb](https://twitter.com/PapersWeLoveSpb)
* [@thought_sync](https://twitter.com/thought_sync)
* [@andreypopp](https://twitter.com/andreypopp)

**Comment by hakutsuru** [comment]
@andreypopp & @termina1: Saint Petersburg is setup - https://github.com/papers-we-love/saint-petersburg

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

When you have had your first meeting, let us know. We can link to your chapter on our website, and share any video, audio or slides from your event with the community.

We have slack, and you are encouraged to join. Welcome aboard.
