### ISSUE TITLE
Chapter Request for Raleigh/Durham North Carolina

### ISSUE THREAD

**Issue by jbelmont** [papers-we-love/organizers#27]
My name is Jean-Marcel Belmont and I am a Software Engineer at Interactive Intelligence at Raleigh-Durham area. I would like to create a local chapter in my area and I tried to create a repo in papers-we-love github organization but when I tried I just created a repo in my own github account. What do I need to do get access. I read the Code of Conduct and I added a README.md here https://github.com/jbelmont/raleigh-durham/blob/master/README.md and code of conduct here https://github.com/jbelmont/raleigh-durham/blob/master/code-of-conduct.md. The meetup that I have is called RDU Computation Club should I create a separate meetup called Papers We Love Raleigh/Durham or can I just use the meetup I created called RDU Computation Club.

**Comment by hakutsuru** [comment]
One of the organizers will add the repo for you, and make you and your colleagues contributors.

But first, I want to see if we can answer your questions. I will ping the organizers on slack, and hopefully get back to you soon!

**Comment by jbelmont** [comment]
@hakutsuru Thank you I look forward to hearing from you

**Comment by jbelmont** [comment]
@hakutsuru Were you able to get any feedback from the organizers?

**Comment by hakutsuru** [comment]
Thanks for checking in. Looks like there was some confusion on our end. We have an organizers meeting tonight, and I will ask about this.

**Comment by jbelmont** [comment]
@hakutsuru Cool thanks

**Comment by hakutsuru** [comment]
@jbelmont Raleigh-Durham is setup - https://github.com/papers-we-love/raleigh-durham

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

@zeeshanlakhani volunteered to discuss how best to manage Meetups -- expect this to happen by mid-week (and ping us this week if it seems we've forgotten somehow).

Welcome aboard!

**Comment by jbelmont** [comment]
@hakutsuru I just accepted the invite and will update the ReadME and Code Of Conduct shortly. 
So @zeeshanlakhani will let me know if I need to create a meetup with Papers We Love Raleigh-Durham or if I can use the RDU Computation Club name instead. Thanks for all your help @hakutsuru.

**Comment by zeeshanlakhani** [comment]
@jbelmont Hello! I'm glad @hakutsuru was able to set you all up with a repo! 

In terms of naming and the like, it's more consistent and generally helpful to name affiliated chapters Papers We Love and to use our assets :). Nonetheless, if you also want to host varying events within RDU Computation Club, maybe those that are Papers We Love-styled could just be called Papers We Love events and get publicizing that way. There are some groups that have take that approach for sure.  

Thank you and please let me know if you have any more questions. This is fantastic to see!

**Comment by jbelmont** [comment]
@zeeshanlakhani I have updated the Meetup name to be Papers We Love Raleigh-Durham and have told members that we operate under Papers We Love Organization and to read the Code-Of-Conduct. Our first meetup is on Tuesday January 10th 2017 https://www.meetup.com/Papers-We-Love-Raleigh-Durham/events/235513891/. After this first meetup we will be listed officially in PaperWeLove Site is this correct?

**Comment by zeeshanlakhani** [comment]
@jbelmont that is correct and thank you so much! Will you be video'ing it?

**Comment by jbelmont** [comment]
@zeeshanlakhani I didn't think about videotaping the session but if I can find recorder and camera person. I will try to do so and could send the recording. To whom should I send the video file for.

**Comment by zeeshanlakhani** [comment]
@jbelmont If you do, I'll add you as a manager on our YT account, https://www.youtube.com/user/PapersWeLove, and you can upload it there!

**Comment by jbelmont** [comment]
@zeeshanlakhani Awesome will let you know if I am able to record thanks. 👍

**Comment by jbelmont** [comment]
@zeeshanlakhani I recorded the session and tried my best to edit the video although I am no professional. It is about 4.57 gigabytes in size and 30 minutes long.

**Comment by zeeshanlakhani** [comment]
@jbelmont I'll add you to our YouTube account so you can upload it. YT will compress it, but it should be fine. What's a good email/account to use? Thanks!

**Comment by jbelmont** [comment]
marcelbelmont@gmail.com

Thanks,

Jean-Marcel Belmont

**Comment by zeeshanlakhani** [comment]
@jbelmont invite sent.

**Comment by jbelmont** [comment]
Got it thanks Zeeshan

**Comment by jbelmont** [comment]
@zeeshanlakhani I just uploaded the video to youtube. Will Raleigh Durham be added to official Papers We Love List of chapters soon?

**Comment by DarrenN** [comment]
@jbelmont - create a PRs like so:

- https://github.com/papers-we-love/papers-we-love/pull/428
- https://github.com/papers-we-love/papers-we-love.github.io/pull/97

Your video is scheduled for a tweet on the PWL account this afternoon.

**Comment by jbelmont** [comment]
@DarrenN 

I just created [papers-we-love/papers-we-love#430](https://github.com/papers-we-love/papers-we-love/pull/430) which got merged
and I also created [papers-welove/papers-we-love.github.io#99](https://github.com/papers-we-love/papers-we-love.github.io/pull/99)

Thanks for tweeting the video on PWL Account 👍
