### ISSUE TITLE
Zurich

### ISSUE THREAD

**Issue by kkourt** [papers-we-love/organizers#28]
> Open an issue on this repo requesting a chapter repo

I would like a repo for a papers-we-love chapter in Zurich.

>  and telling us about yourself, 

I'm Kornilios Kourtis, a researcher at IBM Research in Zurich Switzerland.
More info here: http://kkourt.io

> who is helping you out, 

I've setup a meetup page (https://www.meetup.com/Papers-we-love-Zurich/) with ~~18~~ 75 people already registered. I'm hoping to recruit some of them as co-organizers, but so far it's just me.

> where we can find you online (twitter, etc) 

kornilios@gmail.com, https://twitter.com/kkourt

>  where you're planning on starting the chapter.

Zurich, Switzerland.

**Comment by hakutsuru** [comment]
@kkourt Zurich is setup - https://github.com/papers-we-love/zurich

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by kkourt** [comment]
@hakutsuru Great! Thanks!
