### ISSUE TITLE
Chapter Request for Denver, CO

### ISSUE THREAD

**Issue by hbrumleve** [papers-we-love/organizers#29]
Hello!

My name is Harry and I'm looking to start a PWL chapter in Denver, CO.

I have been in big companies and small companies, but most recently a streaming data startup downtown. We rely heavily on white papers and academia to distinguish our company from others.

Additionally for the last 4 years I have been either directly or indirectly coordinating QCon conferences in New York and San Francisco. It's this experience that taught me to coordinate speakers, set up event spaces, get sponsors, and appreciate the work it takes to make an awesome presentation.

I'm also involved in the Domain Driven Design community here in Denver and I'm dedicated to raising the tide in Denver and showcasing the awesome we already have.

I've spoken to a few like-minded friends about helping me and we have a few places where we go to meetups that would be happy to host our chapter.

I'm super stoked about this opportunity and I'd love to get Denver on the map, comp sci speaking.

Please let me know what I can do to start this up, I'm happy to do as much as needed (and get help, too!)

Cheers, Harry

**Comment by DarrenN** [comment]
@hbrumleve - okay, the Denver repo is ready https://github.com/papers-we-love/denver - you should have received and invitation to join the organizers team. 

Please update the repo with all of the pertinent information, including contact information for yourself and other organizers. Please update the code of conduct as well.

Thanks!
