### ISSUE TITLE
Chapter Request: Nashville, TN

### ISSUE THREAD

**Issue by tsclausing** [papers-we-love/organizers#3]
> Have a chapter repository created within the Papers We Love organization: Open an issue on this repo requesting a chapter repo and telling us about yourself, who is helping you out, where we can find you online (twitter, etc) and where you're planning on starting the chapter. One of the Papers We Love administrators will get in touch with you and once everything is squared away will create the repo for your planned chapter. You will be added to a chapter-organizers team and given read / write access to the repo.

**Where:** Nashville, TN

We will host regular meetings at the [Emma Bistro](http://myemma.com/bistro) or as-needed at [The Skillery](http://www.theskillery.com/).

**Who:**

* Scot Clausing, @tsclausing - Director of Engineering, Emma Inc
* Doug Hurst, @marleys-ghost - Senior Architect, Emma Inc

**Comment by DarrenN** [comment]
@tsclausing okay you're all set - https://github.com/papers-we-love/nashville 

You and @marleys-ghost should have received an invite to join the organizer's team.

**Comment by RichardLitt** [comment]
:+1:
