### ISSUE TITLE
Chapter request: Costa Rica

### ISSUE THREAD

**Issue by andres-bits** [papers-we-love/organizers#30]
Hi,

I am a software developer and a long time lurker of PWL, for years wishing for someone to start a local chapter. Well, I am tired of waiting for someone else and I would like to give it a try here. 

I have a friend, professor at one of our public universities that will help me find a space there for a first one but my idea is to organize them in distinct locations (companies, public and private universities with open attendance of course) to enable people from different communities to attend.

Saludos,

---------
Andrés,
Twitter: @andres_bits

**Comment by DarrenN** [comment]
@andres-bits your repo has been created -> https://github.com/papers-we-love/costa-rica

You should receive an invitation to join the organizers team. Please update the README and the Code of Conduct in your repo. Your README should provide contact information for your chapter.

Let us know if you have any questions!

- D

**Comment by andres-bits** [comment]
Thanks @DarrenN 

I have one: what is the PWL recommendations/policy about the language used in the repos? (For example: Everything in English, provide a translation for the chapter's Code of Conduct. ?)

**Comment by DarrenN** [comment]
We're not beholden to English per se, its really a judgement call for your local community. Translating the README to Spanish for instance, makes total sense. For the Code of Conduct, perhaps add the Spanish translation above the English version.

Twitter: Try to get something that identifies your chapter, like `PapersWeLoveCostaRica` or `PWLCostaRica`. Sometimes cities will have common identifiers in usage like NYC or PDX which you could use as well.
