### ISSUE TITLE
Chapter Request: Lebanon

### ISSUE THREAD

**Issue by saeidw** [papers-we-love/organizers#31]
Hello,

My name is Saeid Al-Wazzan, I'm a software developer here in Lebanon and I'm very interested in starting a local chapter of Papers We Love. I have been involved in the growing local software community but have not organized any events, but I want to do the work to make the chapter a successful and inclusive community for people who are interested in the academic side of software.

I'm getting help with organizing the chapter from the fine folks at ForwardLB, a local co-working space. The location is an excellent environment for presenting and discussing papers.

You can find me online on Twitter ([@saeidw](https://twitter.com/saeidw)) and my email address is saeid [dot] wazzan [at] nonsingular.net. I have also joined the paperswelove Slack and will be available there.

**Comment by DarrenN** [comment]
Hi @saeidw - your repo is ready -> https://github.com/papers-we-love/lebanon

Please update the README and the Code of Conduct with information specific to your chapter, ensuring there is contact information for yourself and your fellow organizers.

Once you have your first meetup you can open a PR on https://github.com/papers-we-love/papers-we-love and https://github.com/papers-we-love/papers-we-love.github.io to get your chapter listed.

Thanks!

- D
