### ISSUE TITLE
Chapter request: Chennai, India

### ISSUE THREAD

**Issue by ganesh-srinivas** [papers-we-love/organizers#32]
Chennai has a large tech crowd as well as several well-respected academic establishments (IIT Madras, Chennai Mathematical Institute, Institute of Mathematical Sciences, etc.). I would like there to be a Papers We Love chapter here.

My name is [Ganesh Srinivas](http://ganesh-srinivas.github.io) (gs401 [at] snu [dot] edu [dot] in), and I'm nearly done with my bachelors degree in Computer Science and Engineering. I have interned in academia, at a startup, and right now, I'm interning at a large tech company. I'm wrapping up an undergrad research project in music information retrieval (recognize a song when someone hums it). This project led me to study and apply the latest developments in deep learning. That whole field is advancing at a galloping pace, and I've been aching to discuss some exciting recent results with other people and bounce ideas off them. That is one of the selfish reasons for wanting to start a PWL chapter here. Aside from machine learning, I also keep up with other areas within computer science (computer networks, privacy, etc.).

I have some experience in organizing events. I was President of the ACM Student Chapter at my university from November 2015 to November 2016. During that time, I was responsible for organizing two research talks by professors, creating and teaching a tutorial series for university students (basic Python, bash, machine learning, etc.), hosting programming competitions, and doing other CS outreach activities.

I have help from Benoy Thomas John (benoytj [at] gmail [dot] com).

Location: Coffee shops (I know one that has hosted meetups).

**Comment by DarrenN** [comment]
Hi @ganesh-srinivas  - your repo is ready -> https://github.com/papers-we-love/chennai

You should receive an email inviting you to join the organizers team. Please update the README and the Code of Conduct with information specific to your chapter, ensuring there is contact information for yourself and your fellow organizers.

Once you have your first meetup you can open a PR on https://github.com/papers-we-love/papers-we-love and https://github.com/papers-we-love/papers-we-love.github.io to get your chapter listed.

Thanks!

- D
