### ISSUE TITLE
Wellington

### ISSUE THREAD

**Issue by gerred** [papers-we-love/organizers#33]
Hi, all.

@ferrouswheel and I have just started a PWL Wellington meetup! Its located here:

https://www.meetup.com/Papers-We-Love-Wellington/

We're software engineers here in Wellington. Originally, I'm from Colorado where I've organised meetups in the past. In particular, I'm very interested in PLT and Distributed Systems. @ferrouswheel has a particular interest in machine learning.

We'll be adopting the main Code of Conduct, have a Twitter account already located at: https://twitter.com/paperswelovewlg

We'd love to get a chapter repo going, and I'm joining the Slack group now.

**Comment by hakutsuru** [comment]
@gerred, @ferrouswheel: Wellington is setup - https://github.com/papers-we-love/wellington

Once you accept the invitation for the organizers team please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by DarrenN** [comment]
Slack signup http://papersweloveslack.herokuapp.com/

**Comment by DarrenN** [comment]
@gerred, @ferrouswheel have you accepted the invites and updated your repo?

**Comment by DarrenN** [comment]
@hakutsuru it appears this chapter has died https://www.meetup.com/Papers-We-Love-Wellington/
