### ISSUE TITLE
Chapter request for Medellín, Colombia

### ISSUE THREAD

**Issue by c4milo** [papers-we-love/organizers#34]
My name is Camilo Aguilar, I can be found at https://twitter.com/c4milo. Along with @castillobgr and @sescobb27 we would like to start the chapter in Medellín, Colombia. 

Details about the first meetup can be found at: https://www.meetup.com/paperswelovemde/events/238392836/ (Spanish)

Twitter: https://twitter.com/paperswelovemde

Thanks!

**Comment by hakutsuru** [comment]
@c4milo, @castillobgr, @sescobb27: Medellin is setup - https://github.com/papers-we-love/medellin

Once you accept the invitation for the organizers team, please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by DarrenN** [comment]
Slack signup http://papersweloveslack.herokuapp.com/

**Comment by c4milo** [comment]
@DarrenN, @hakutsuru thank you! We just updated the README and Code of Conduct.
