### ISSUE TITLE
New Chapter in São Paulo

### ISSUE THREAD

**Issue by icaromedeiros** [papers-we-love/organizers#35]
Hello, I am [Ícaro Medeiros](http://www.icaromedeiros.com.br) and I would like to start the São Paulo chapter in Brazil. I am a data scientist, currently working at Telefônica | Vivo (largest telecom in Brazil).

@raulmagno and @ispmarin will be helping me.

I've cried a meetup page https://www.meetup.com/pt-BR/papers-we-love-sp/ and a Slack channel for the chapter http://paperswelovesp.slack.com.

On the next days/weeks my intention is to make the chapter public in local meetups and ask people to join the meetup/Slack channels.

Twitter: http://twitter.com/icaromedeiros

**Comment by ispmarin** [comment]
Hey, @ispmarin here. Excited of being part of this chapter here in SP!

**Comment by hakutsuru** [comment]
@icaromedeiros, @raulmagno, @ispmarin: Sao Paulo is setup - https://github.com/papers-we-love/sao-paulo

Once you accept the invitation for the organizers team, please update the Readme and Code of Conduct with your chapter's information.

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by icaromedeiros** [comment]
Thank you so much. @hakutsuru do I need an invitation to the paperswelove.org email so that I can login into the world-franchise Slack? Sorry if it's a dumb question with a manual written somewhere.

**Comment by DarrenN** [comment]
@icaromedeiros you can sign-up here http://papersweloveslack.herokuapp.com/
