### ISSUE TITLE
Chapter request Leuven

### ISSUE THREAD

**Issue by rutgerclaes** [papers-we-love/organizers#36]
Hello I'm Rutger Claes (@rutgerclaes).  Former researcher at University of Leuven, now Big Data and Data Science lead at Cegeka.  Together with @mariohct ‏we're starting a chapter in Leuven.

Meetup: https://www.meetup.com/Papers-We-Love-Leuven/
Twitter: https://twitter.com/pwl_leuven

Thanks.

**Comment by hakutsuru** [comment]
@rutgerclaes: Leuven is setup - https://github.com/papers-we-love/leuven

Once you accept the invitation for the organizers team, please update the Readme and Code of Conduct with your chapter's information.

(I was unable to add Mario Henrique Cruz Torres as an organizer, feel free to do this...)

We have slack, and you are encouraged to join. Welcome aboard.

**Comment by DarrenN** [comment]
Slack signup http://papersweloveslack.herokuapp.com/
