### ISSUE TITLE
Rio de Janeiro City Chapter

### ISSUE THREAD

**Issue by lsmag** [papers-we-love/organizers#37]
Hello,

I'm Lucas Sampaio (twitter lsmagalhaes), backend engineer at LaterPay and together with @arruda (twitter 4rrud4), developer at OList, we'd like to open a new PWL chapter in Rio.

We already created a meetup.com page ( https://www.meetup.com/Papers-We-Love-Rio/ ) and a Discord group ( discord.gg/WAHKDdG ). We're ready to make the new chapter public to organize the first meetup.

**Comment by hakutsuru** [comment]
@arruda, @lsmag: Rio de Janeiro is setup - https://github.com/papers-we-love/rio-de-janeiro

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by DarrenN** [comment]
@arruda, @lsmag have you accepted the invites and updated your chapter repo?
