### ISSUE TITLE
Iowa City Chapter Repo Request

### ISSUE THREAD

**Issue by geemus** [papers-we-love/organizers#38]
Hello!

I'm Wesley Beary a developer at Heroku, open sourcer and community organizer. I've been really interested in papers-we-love for some time to keep learning new stuff for myself and also to help me bridge the gap between our local developer and academic/university communities.

I'm geemus on twitter and most other places (including the papers-we-love slack, though I've just been lurking rather than chatting actively so far).

I've reached out to my local developer community (http://techcorridor.io/) with a survey and got back a number of folks interested in participating or presenting (and one co-organizer). I hope to continue to grow that number, but I think it's a good start. We also have a channel on the techcorridor.io slack to discuss and organize as needed.

I hope to meet about once a month, probably either at the local co-working space or public library.

Just let me know if you need anything else from me, I look forward to more learning and sharing.

Thanks!
wes

**Comment by hakutsuru** [comment]
@geemus: Glad to hear organizing your new chapter is going well!

You and your co-organizer would normally both be invited as administrative collaborators on the new chapter repo. Does your co-organizer use github?

If so, please provide their username, otherwise, I can setup the new repo with you as the sole team member. Thanks.

**Comment by geemus** [comment]
@hakutsuru sounds good. If you could invite myself and @jeddeloh for now that would be great.I hope to wrangle more co-organizers/github handles, but that should get us started. Thanks!

**Comment by hakutsuru** [comment]
@geemus, @jeddeloh: Iowa City is setup - https://github.com/papers-we-love/iowa-city

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

You are encouraged to join (or continue lurking in) our slack --
http://papersweloveslack.herokuapp.com/

We are going to be in St. Louis in September, so please let associates know if you think they might be interested -- http://pwlconf.org 

Welcome aboard.

**Comment by geemus** [comment]
Awesome, we've done our initial revisions and hope to get our first meetup in shortly. Thanks!
