### ISSUE TITLE
Eindhoven city chapter request

### ISSUE THREAD

**Issue by jimdsouza** [papers-we-love/organizers#39]
Hi, 

I'm Jim Aldon D'Souza, a research engineer at TomTom in Eindhoven, Netherlands, I've been attending and hosting reading groups for a while, and I've always been fascinated by the work papers we love does. It's sad that there isn't a local chapter in my city, and I'd love to change that.

I'm @jimdsouza on twitter, and Eindhoven being a tech hub of the Netherlands, there is interest in a CS reading group here. 

We plan to host the meetups at the Technical University of Eindhoven's library meeting spaces.

**Comment by hakutsuru** [comment]
@jimdsouza Eindhoven is setup - https://github.com/papers-we-love/eindhoven

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
