### ISSUE TITLE
Kathmandu, Nepal

### ISSUE THREAD

**Issue by bistaumanga** [papers-we-love/organizers#4]
Where: Kathmandu, Nepal

We will host regular meetings by requesting for venues at different software companies or educational institutions in Kathmandu or its adjacent places.

Who:
Umanga Bista, @bistaumanga - Associate Research Engineer, LogPoint A/S, Lalitpur, Nepal
Sudip Kafle, @KafleSudip - CTO and Cofounder, Phunka Technologies, Kathmandu, Nepal

**Comment by DarrenN** [comment]
@bistaumanga your repo is ready: https://github.com/papers-we-love/kathmandu

You should have received an invite to join the organizers team. Please update the `README.md` and `code-of-conduct.md` file in the repo.
