### ISSUE TITLE
Barcelona Chapter

### ISSUE THREAD

**Issue by jomsdev** [papers-we-love/organizers#40]
Hi,

I am Jordi Montes, a Researcher engineer at [Barcelona Supercomputing Center](https://www.bsc.es/), Spain (just moved here from IBM Research in Almaden, CA). I have always been fascinated about how much you can learn when meeting other people. The quantity of meetups that were available in San Jose were incredible but here, in Spain, things are a bit different. Even when Barcelona is becoming a hub for startups and research centers there is not a papers we love Barcelona. I feel like changing that.

We want to organize it in different places to reach more people. The idea is use some public university spaces (BarcelonaTech) and maybe use the office of some startups (it depends on how much we succeed)

You can find me on twitter and github under the same nick @jomsdev 

We already have a [meetup page](https://www.meetup.com/papers-we-love-bcn) and we are discussing about the topic of our first event.

Do not hesitate to reach me if you need anything,

Jordi.

**Comment by hakutsuru** [comment]
@jomsdev Barcelona is setup - https://github.com/papers-we-love/barcelona

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
