### ISSUE TITLE
Request for an Atlanta chapter

### ISSUE THREAD

**Issue by akalra** [papers-we-love/organizers#41]
Hi -- 

I'm Ankur (akalra lots of places, @tadkalagake on Twitter), and I run Hop Labs (www.hoplabs.com) -- an ML consulting company in Atlanta, GA. We work closely with professors and researchers at Georgia Tech, our sweet spot is projects that are commercial applications of recent CS research. 

I'd like to start an Atlanta chapter of PWL, and use our offices (and collaborators at GT) to get it seeded. There's a strong academic and general technical community in Atlanta, and we're fortunate to be one of a very few companies that get to interact deeply with both sides. We'd love to encourage deeper connections across the academic/industry divide in our local community.

Happy to provide any additional context necessary, please do let me know if you need anything else,

Thanks!

Ankur

**Comment by DarrenN** [comment]
Hi @akaira, do you have anyone else helping out or just yourself for now?

**Comment by DarrenN** [comment]
@hakutsuru talked to @akalra on Slack, I think Atlanta is good to go for a repo.

**Comment by hakutsuru** [comment]
@akalra: Atlanta is setup - https://github.com/papers-we-love/atlanta

Once you accept the invitation as a collaborator, please update the Readme and Code of Conduct with your chapter's information.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by jerseybbq** [comment]
Hi - just discovered this chapter request when I was going to sign up myself! Not sure if anything has happened since Sept. We (fullstory.com) are happy to sponsor/host an Atlanta chapter; we have good meeting space and an eng/data team with a strong research bent.

**Comment by akalra** [comment]
Awesome, glad to hear that. I know some of the folks at FullStory from grad school at GT, should have expected that you guys would be a good fit ;)

Been working with some folks offline to start getting things lined up to kickoff post holidays. If you (or someone else at FullStory) is interested in helping with organization / logistics, happy to include you. Can you send me an email at ankur@hoplabs.com please?

Thanks!

Ankur
