### ISSUE TITLE
Guadalajara MX Chapter

### ISSUE THREAD

**Issue by miker1423** [papers-we-love/organizers#42]
Hi, 
I'm Miguel Pérez García (@youmike, twitter), and I'm a student at Tecnológico de Monterrey here in Guadalajara, and with a pair of my friends (@chrismarquez & @eldelcesar) would like to start a chapter in our city, hosting the meetings at the university campus. We are backed up by the university and we are looking forward to gather the other universities, research centers and the industry in general. 
The reason to open the chapter is because we think that even though Guadalajara has a lot of tech industry, the culture of reading papers is not as strong as it should be; so the purpose of the chapter is to spread it out not only in the city, but in the whole country. 😃

**Comment by hakutsuru** [comment]
@miker1423, @chrismarquez, @eldelcesar -- Guadalajara is setup - https://github.com/papers-we-love/guadalajara

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

In your issue, you wrote of spreading collaboration between academia and industry, and this is the Papers We Love mission. We will be interested in hearing about your experience and challenges. We believe our Code of Conduct is part of a larger community evolution, and we hope that all new chapter organizers will embrace our efforts at inclusiveness and mutual respect. 

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
