### ISSUE TITLE
Athens, Greece chapter

### ISSUE THREAD

**Issue by greenonion** [papers-we-love/organizers#44]
Hey guys,

I'm Nikos (@greenonion here and on the papers we love Slack, @nikosfertakis on twitter). I live in Athens, Greece, I am a software engineer and lead the Search team at Skroutz (www.skroutz.gr, also www.scrooge.co.uk and www.alve.com) which is a price comparison engine and the largest greek website. Together with my friend and colleague Giorgos (@chief here, @giorgostsiftsis on twitter) we're thinking of starting a local Papers We Love chapter. We intend to host (at least for the first few times) the meetups in our company offices. We have successfully hosted other meetups before (Ruby, Clojure etc.), and George was also part of the team that organised EuRuKo 2013 which took place in Athens. We think of PWL as a great opportunity for community building around ideas, something we feel Athens really needs. Our goal is to invite people from both industry and academia to give presentations.

We'll be glad to provide any additional details you might need, and looking forward to hearing from you.

Thanks a lot,

Nikos

**Comment by hakutsuru** [comment]
@greenonion, @chief - Athens is setup - https://github.com/papers-we-love/athens

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by greenonion** [comment]
Hey @hakutsuru, thanks a lot! We both take these things seriously and will work towards making certain the community is inclusive and positive.
