### ISSUE TITLE
Berlin

### ISSUE THREAD

**Issue by glaukommatos** [papers-we-love/organizers#45]
Greetings friends,

I'm Haskell, a new organizer of the Berlin Papers We Love chapter which I am excited to help re-activate. I am a software developer living currently in Berlin and working for ThoughtWorks Germany. At the moment I am the only active organizer as the existing organizers have not had enough time recently, but I miss being able to attend PWL meetups so I'm happy to step in for as long as I can.

I am to be found on Twitter by the handle @glaukommatos or also as @haskell on the paperswelove slack. I have secured a location at the ThoughtWorks Berlin office for our first Meetup after the two year hiatus of the Berlin chapter and have started reaching out for interested presenters.

Thank you for your time,
Haskell Pointer

**Comment by hakutsuru** [comment]
@glaukommatos, @mkleen, @igorw -- Berlin is setup - https://github.com/papers-we-love/berlin

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

Haskell, glad to hear the Berlin chapter has your enthusiasm. Early PWL chapters may have gotten started before we began emphasizing our Code of Conduct. We hope every chapter (new and old) will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

Welcome aboard.
