### ISSUE TITLE
Porto Alegre, Brazil chapter

### ISSUE THREAD

**Issue by rafaelpsouza** [papers-we-love/organizers#46]
Hi guys,

I'm Rafael Souza @rafael_psouza I live in Porto Alegre, Brazil and I'm a software engineer and Ubots Co-founder. I think Papers We Love is a greate opportunity for the local community and I'm thinking of starting a local chapter (already invited some friends to helpe me).

I already gave talks and supported local software development events (like Qcon Rio, and The Developers Conference) and I'll be glad to host PWL Porto Alegre!

**Comment by sachakilinski** [comment]
i´m glad being invited by @rafaelpsouza to help in this chapter!

I Also live in Porto Alegre. I´ve graduated in applied maths but work as a software engineer.
Although i´ve only organized small events so far, I see hosting PWL as a great opportunity to give back to the community.

**Comment by DarrenN** [comment]
@hakutsuru

**Comment by hakutsuru** [comment]
@rafaelpsouza, @sachakilinski -- Porto Alegre repo has been created - https://github.com/papers-we-love/porto-alegre

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by rafaelpsouza** [comment]
Thaks @hakutsuru! I'm glab to join PWL.

We're going to update the Readme and Code of Conduct soon and also start to invite people to our local chapter.
Hope we'll have the first meetup early 2018.

**Comment by pmargreff** [comment]
@rafaelpsouza @sachakilinski Hey there guys, I'm also living at Porto Alegre, you have any idea about starting the meetups? I surprised myself about an issue for Porto Alegre. 

Can you add me on repo, or pass me some contact to chat about making it happen?

**Comment by DarrenN** [comment]
@rafaelpsouza, @sachakilinski - It looks like you haven't run any meetups since this repo was created. @pmargreff would like to take over the chapter. If we don't hear from in the next couple of days we're going to hand it over to him to run.

Thanks,

PWL Orgs

**Comment by hakutsuru** [comment]
@pmargreff Based on discussions here, I have invited you as an admin on the repo. Good luck organizing the chapter, please reach out on slack with any questions (or reply here).
