### ISSUE TITLE
Rio de Janeiro, Brazil

### ISSUE THREAD

**Issue by crissilvaeng** [papers-we-love/organizers#47]
Hi, readers!

We're Cristina Silva (twitter: crissilvaeng) and @ThaynaraSantos, both computer engineering students and software developers in Rio de Janeiro, we'd like to make oficial the new PWL chapter in Rio.

We created a meetup.com page (https://www.meetup.com/pt-BR/papers-we-love-rio-de-janeiro/) that is already in operation.

Best regards,
Cristina Silva

**Comment by crissilvaeng** [comment]
Hi!

Any news?

**Comment by hakutsuru** [comment]
Sorry, this got caught up in holidays here.

You write this is "the new PWL chapter in Rio", and I am slightly confused. Did you see the Rio chapter we set up in July?

https://github.com/papers-we-love/organizers/issues/37

Does this new chapter have any relation to the other?

**Comment by crissilvaeng** [comment]
Hi!

No, because the other chapter in Rio is deprecated and no one respond anymore or take care of it, so we decided to create a new one.

The new chapter have acceptance of the community and now it have 89 members. Where there have already been four meetings and there are three others already scheduled.

Sorry for the mess.

**Comment by hakutsuru** [comment]
Thanks for the update. This is an odd situtation, so I appreciate your patience.

@arruda, @lsmag: Do you have any input? It would be ideal if you could collaborate with this new team, and/or notify your Meetup members about this new group.  

If the original team will not be holding meetings, I would like to transfer administration of the chapter repo to the new team this weekend.

Does any disagree? @DarrenN, @jeremyheiler, @zeeshanlakhani

(We are also discussing this in private channels...)

**Comment by DarrenN** [comment]
@hakutsuru please make @crissilvaeng and @ThaynaraSantos administrators of the existing repo - thank you.

@crissilvaeng  - please update the README and the Code of Conduct in the repo when you have access. We ask that you ensure members are aware of the code of conduct. We can make you a set of images to use for twitter / meetup.com / etc.

Thanks again everyone.

**Comment by hakutsuru** [comment]
@crissilvaeng, @ThaynaraSantos — You are both invited as Admins on https://github.com/papers-we-love/rio-de-janeiro

**Comment by crissilvaeng** [comment]
Hello guys!

I have already updated the [Code of Conduct](https://github.com/papers-we-love/rio-de-janeiro/blob/master/code-of-conduct.md) and the [README](https://github.com/papers-we-love/rio-de-janeiro/blob/master/README.md), also put the translation of both in the repository.

I would love this set of pictures! Can you guys do it for us?

For now we're only using Meetup, we have no Twitter or any other social networks for Chapter.

**Comment by DarrenN** [comment]
@crissilvaeng Would it work to make the images Papers We Love Rio or do you prefer Papers We Love Rio de Janeiro ?

**Comment by crissilvaeng** [comment]
Hi, @DarrenN.

Papers We Love Rio de Janeiro, i think...

**Comment by DarrenN** [comment]
Thanks @crissilvaeng - should be able to get something together over the weekend.

**Comment by crissilvaeng** [comment]
Thanks you, @DarrenN!

**Comment by DarrenN** [comment]
@crissilvaeng you can pick up assets here -> https://www.dropbox.com/s/n5k3ctvcfah3mno/pwl-rio.zip?dl=0
