### ISSUE TITLE
Chapter Request: Porto, Portugal.

### ISSUE THREAD

**Issue by ordepdev** [papers-we-love/organizers#49]
Hey,

I'm Pedro, I work as a Software Engineer at [Farfetch](farfetch.com) and I'm also pursuing a Master's Degree at [Faculty of Engineering, University of Porto](https://sigarra.up.pt/feup/en). You can find more info at [ordepdev.me](ordepdev.me).

I'm about to start a new chapter in Porto, Portugal. It will be the first in Portugal 🎉  I'm starting the chapter by myself, but there are one or two people interested in co-organizing. There are several tech companies that are available to host meetups and I will try to reach a few of them.

As soon as you approve, I'll create the meetup page 👍 

Thanks,
Pedro.

**Comment by hakutsuru** [comment]
@ordepdev -- Porto is setup - https://github.com/papers-we-love/porto

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment awareness in the news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by ordepdev** [comment]
Done. All set @hakutsuru. Thanks 👍
