### ISSUE TITLE
Chapter Request: Iasi, Romania

### ISSUE THREAD

**Issue by adrianp** [papers-we-love/organizers#5]
Where: Iasi, Romania

Who:
* Adrian-Tudor Panescu, MSc, Software Engineer at [Cynny](https://www.cynny.com/)/ [Endava](http://www.endava.com/),  @adrianp
* Adrian Burlacu, PhD, Associate Professor at [TUIASI](http://www.tuiasi.ro/en/), @AdrianBurlacu
* Alexandru Archip, PhD, Assistant Professor at [TUIASI](http://www.tuiasi.ro/en/), @alexarchip
* Alexandra Adam, HR Manager at [Cynny](https://www.cynny.com/), helping us on the org side as needed; sorry, no Github account for her  

[Meetup page](http://www.meetup.com/Papers-We-Love-Iasi/); the current plan is to have the first meeting on December 15.

**Comment by DarrenN** [comment]
@adrianp your repo has been setup: https://github.com/papers-we-love/iasi

You should have received invites to join the organization which will give you, @alexarchip and @AdrianBurlacu write access.  Please update the files in the repo along [these guidelines](https://github.com/papers-we-love/organizers). 

Thanks and welcome aboard!
