### ISSUE TITLE
Cairo, Egypt

### ISSUE THREAD

**Issue by youssefsharief** [papers-we-love/organizers#50]
Hi,
I am Youssef Sherif. I am software architect and a machine learning enthusiast. You could reach me online through Linkedin here. [https://www.linkedin.com/in/youssefsharief](url). 

Omar Amin, the co-organizer, is a Machine learning engineer and a Teaching and Research Assistant. He is currently coducting his Master's in CS. You could reach him online here https://www.linkedin.com/in/omar-moh-amin/

I have already started a meetup page https://www.meetup.com/Papers-We-Love-Cairo and a facebook page https://www.facebook.com/groups/556898091339688/about/ but probably will remove one of them.

**Comment by hakutsuru** [comment]
@youssefsharief -- Cairo is setup - https://github.com/papers-we-love/cairo

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

Please add Omar Amin as a collaborator on the repo (if Omar Amin has a github account).

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by youssefsharief** [comment]
Thank you. Done

**Comment by youssefsharief** [comment]
Thank you. Done.
