### ISSUE TITLE
Copenhagen chapter

### ISSUE THREAD

**Issue by berianjames** [papers-we-love/organizers#51]
Hi, We're a group of researchers, engineers and data scientists working in industry in Copenhagen, Denmark. We've been running an informal journal club for a while on topics in machine learning, engineering and statistics and were surprised to find that Copenhagen doesn't have a chapter already. We're definitely ready to host one! We've a good network and places to host, and a great backlog to get started with.

[Berian](https://www.linkedin.com/in/berianjames/) - @berianjames, Head of AI, Maersk Digital
[Cem](https://www.linkedin.com/in/cemezberci/) - @ezbercih, CTO, Maersk Digital
[Barry](https://www.linkedin.com/in/barrynorton) - @BarryNorton, Research Director, Milestone Systems
[Benjamin](https://www.linkedin.com/in/benjaminhoyer), Engineer, Google Cloud

**Comment by hakutsuru** [comment]
@berianjames, @ezbercih, @BarryNorton -- Copenhagen is setup - https://github.com/papers-we-love/copenhagen

As you are all Admin for this repo, you may add Benjamin as a collaborator at your convenience.

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment persistently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
