### ISSUE TITLE
Chapter Request: Bhubaneswar, India

### ISSUE THREAD

**Issue by shivank01** [papers-we-love/organizers#52]
Bhubaneswar has large tech crowd as well as several well-respected academic institutes(IIT, IIIT ,Cet, etc.).  I would like there to be a Papers We Love chapter.
My name is [Shivank Pathak](https://shivank01.github.io)(shivankpathak357[at]gmail[dot]com), I am the student of Bachelor of Technology from IIIT Bhubaneswar.  I have always been fascinated about how much you can learn when meeting other people. I have some experience in organizing events. I am the secretary of the ACM Student Chapter and an active member of [IIIT-Bh Programming Society](https://p-society.herokuapp.com/). IIIT-Bh Programming society Bhubaneswar has organised several events in our university. Several members of this society will help setting up the papers-we-love bhubaneswar chapter. There are many people who have active background in the research. Some of the members have also published research papers at reputed venues. 

We will be holding our first meetup in mid August.
Location- IIIT Bhubaneswar

**Comment by hakutsuru** [comment]
@shivank01 -- Bhubaneswar is setup - https://github.com/papers-we-love/organizers

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information.

Please add other co-organizers as admins when these have been established, as you did not state who would be helping you with this. Also, when inquiring about issues or pull requests, a bit of patience is helpful.

With abuse and harassment constantly in the news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by shivank01** [comment]
Thank You @hakutsuru . I will update the Readme and Code of Conduct and also add our other co-organizers by today.
