### ISSUE TITLE
Cairo, Egypt

### ISSUE THREAD

**Issue by youssefsharief** [papers-we-love/organizers#53]
Our first event was yesterday. Here is the event link. https://www.meetup.com/Papers-We-Love-Cairo/events/253010441/. I hope you could add a link for our meetup on paperswelove.org and on the main GitHub page.

**Comment by hakutsuru** [comment]
We have been a bit busy organizing PWLConf, but I will ping the team about this tonight. Hopefully, we can get this done soon.

**Comment by DarrenN** [comment]
@youssefsharief please open two PRs:

- Add your chapter to https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/data/chapters.json and create a `_cairo.erb.markdown` file similar to https://github.com/papers-we-love/papers-we-love.github.io/blob/middleman/source/partials/chapters/_rio-de-janeiro.erb.markdown
- Create another PR to add your chapter to the README in https://github.com/papers-we-love/papers-we-love/blob/master/README.md

**Comment by youssefsharief** [comment]
Ok done.

@hakutsuru  Please also merge the pull request for this repo https://github.com/papers-we-love/cairo

**Comment by hakutsuru** [comment]
The website is generated periodically, your changes have been merged, so Cairo should appear on the site soon. I am closing this now, but feel free to comment further with any concerns.
