### ISSUE TITLE
Chapter Request: KTR, India

### ISSUE THREAD

**Issue by arjunbahuguna** [papers-we-love/organizers#54]
Hi PWL,
I'm a Computer Science undergraduate studying at SRM University, Kattankulathur (KTR). Me and my team have been conducting weekly paper-reading sessions for the past two years, as part of activities of [Next Tech Lab](https://nextech.io/home) & SRM-ACM Student Chapter. We've conducted approximately 50 such sessions over two academic years, with two to three papers being discussed in each session. More details about the structure can be found [here](https://www.reddit.com/r/MachineLearning/comments/7ny3s8/d_do_you_have_a_paper_reading_group_at_your/ds5ibk3/).

We wish to start a PWL chapter at our university in Kattankulathur, and hold weekly meetups. We plan to record our talks for PWL's YouTube & MixCloud channels. We're interested in knowing if PWL will be providing stickers, swag, tickets to PWLConf, or any such benefits for the PWL-KTR community so we can attract meetup participants.

Thanks,
Arjun Bahuguna
arjun.bahuguna@nextech.io

**Comment by arjunbahuguna** [comment]
Thank you for the information. When can we go ahead with creation of the repo?

**Comment by hakutsuru** [comment]
I should have time to do this by sometime tomorrow.

**Comment by hakutsuru** [comment]
@arjunbahuguna -- Kattankulathur is setup - https://github.com/papers-we-love/kattankulathur

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. You should also eventually add other collaborators with write/admin authority.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- please customize your Code of Conduct, and let us know if our default CoC be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
