### ISSUE TITLE
Chapter Request: Little Rock, AR

### ISSUE THREAD

**Issue by dsharp70** [papers-we-love/organizers#55]
Hello.  My name is Daniel Sharp.  I've been a professional developer since the 90s working from the bottom up inside of the corporate structure before moving into freelance work.  There is a small but growing startup movement locally, and we need more opportunities to connect with the broader tech world.  A local PWL Chapter would play a critical part in helping to fill that gap.  

I run my business from the Little Rock Tech Park, a space sponsored and funded by the state as part of an initiative to bring more tech startups to the state.  I have recruited two other startup entrepreneurs from the tech park who are willing to help me run a local chapter.  I'm also confident that the Little Rock Tech Park will provide meeting spaces as needed.

You can find me on Twitter as @SharpSolDaniel, on [LinkedIn](www.linkedin.com/in/daniel-sharp-24823023) and my [personal site](DanielSSharp.com).

Thank you!

Daniel Sharp

**Comment by hakutsuru** [comment]
@dsharp70 Somehow I missed this, we should have gotten back to you in less than 10 days. Github was having notification issues, or I was careless. In any case, why did you close this? If you are still considering starting a chapter, I would handle the issue asap.

**Comment by hakutsuru** [comment]
@dsharp70 -- Little Rock is setup - https://github.com/papers-we-love/little-rock

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information (and add other organizers as collaborators, when appropriate).

We offer help with branding graphics for social media, and the chapter can be listed on our website after your first meeting. You can find discussions about this in other issues/PRs and in our slack.

With abuse and harassment recently in the news, we hope every new chapter will embrace our mission to foster open and accepting communities -- please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
