### ISSUE TITLE
Chapter Request: Sydney, Australia

### ISSUE THREAD

**Issue by OzanGunaydin** [papers-we-love/organizers#56]
Hello,
My name is Ozan Gunaydin. I am an Electrical Engineer and work on embedded software & hardware development. I love reading science history and have recently come across Papers We Love and was surprised that there was no chapter here in Sydney. I work for a startup at the moment inside Sydney Startup Hub building which houses many co-working spaces supported by government and there is a big ecosystem of engineers and developers around. I believe a local PWL chapter could be very active and beneficial to everyone. Many meetup events take place in this building daily and I believe finding meeting space wouldn’t be an issue.
You can find me on [Linkedin](https://www.linkedin.com/in/ozangunaydin/) and on Twitter @Dozimas.

Cheers!
Ozan Gunaydin

**Comment by hakutsuru** [comment]
@OzanGunaydin -- Sydney is setup - https://github.com/papers-we-love/sydney

Once you accept the invitation as a collaborator, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment frequently in the news (nearby in the USA), we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by OzanGunaydin** [comment]
@hakutsuru Thanks a lot!

I am reading the Code of Conduct and will update the Readme in Sydney chapter.

Cheers
