### ISSUE TITLE
Eindhoven city chapter repo transfer?

### ISSUE THREAD

**Issue by mmzsource** [papers-we-love/organizers#58]
My name is Maarten Metz. I'm a principal software engineer at Philips Research in Eindhoven. I have been developing software professionally for over 20 years. Before that, I've studied human-computer interaction at the Technical University in Eindhoven. I love reading papers and applying them in day-to-day practice. My twitter account can be found here: https://twitter.com/MMz_ 

Eindhoven seems to be the perfect place for a papers we love chapter. It's a high tech hub with companies like Philips, ASML, TomTom, NXP, and also a technical university. Therefore I wasn't surprised Jim Aldon D'Souza already requested a chapter: https://github.com/papers-we-love/organizers/issues/39 

However, the repo hasn't seen any new commits for a while (https://github.com/papers-we-love/eindhoven) and Jim seems to have moved to another continent: https://twitter.com/jimdsouza 

I've tried to reach Jim via twitter ( https://twitter.com/MMz_/status/1098176037744246784 & https://twitter.com/MMz_/status/1103053637985673216 ) and via his papers we love eindhoven slack channel. I've had no success in contacting him yet. 

I'd like to get started with the paperswelove Eindhoven chapter. I can host the meetings on the high tech campus in Eindhoven and I have a lot of connections to other paper lovers in the area. It would help me to organise and communicate from the official paperswelove/eindhoven repository.

What are your thoughts on transferring the paperswelove/eindhoven repository?

**Comment by DarrenN** [comment]
Hi @mmzsource - thanks for reaching out. We'll make another attempt to contact @jimdsouza and then proceed with the transfer over to you if we can't make contact.

**Comment by DarrenN** [comment]
Looks like you made contact with @jimdsouza https://twitter.com/jimdsouza/status/1106184183024701447

**Comment by jimaldon** [comment]
Hi @mmzsource wonderful to see you'd like to participate actively! I'm not Eindhoven temporarily, but I'd me more than happy to assist you any way I can.

**Comment by jimaldon** [comment]
You couldn't reach me on github because I changed my username to @jimaldon

Meanwhile, I've added you as a contact person for papers-we-love Eindhoven

**Comment by jimaldon** [comment]
DM me on Twitter @jimdsouza

**Comment by mmzsource** [comment]
> Hi @jimaldon good to be in contact. I have a couple of questions for you and I can imagine you have some for me too. This github issue is probably not the best place to discuss them ... maybe DM on twitter? Or email?

**Comment by mmzsource** [comment]
@jimaldon to DM you need to follow me (temporarily at least)
