### ISSUE TITLE
Chapter Request: Kochi,India

### ISSUE THREAD

**Issue by picklehari** [papers-we-love/organizers#59]
Kochi is a city in the southern part of India, with a substantial tech crowd, interested in a whole spectrum of different technologies. Although a lot of tech-based communities, functions here, a research-based community is something this city is lacking and hence this request.

My name is Hariraj K. I am a student at my pre-final year of my bachelor's degree. I am also an entrepreneur who someday wishes to build my startup to a massive R&D firm. I have done a few projects on logistics,  data science, and genetic algorithms. You can find me on twitter as [picklehari](https://twitter.com/picklehari/) or on LinkedIn as Hariraj K.

I also happen to be the founder of FOSSMEC a small college community, that promotes open sourced technology. The success of this small organization makes me confident enough that I can put myself together a passionate team and build this chapter

**Comment by hakutsuru** [comment]
Will set this up within a couple days...

**Comment by hakutsuru** [comment]
@picklehari -- Kochi is setup - https://github.com/papers-we-love/kochi

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

After a chapter has had its first meeting, we can add it to our site <https://paperswelove.org>. Info about this can be found in closed issues (or ask via issue/email/slack). Discussions on managing chapters and papers of interest have recently been in our #general channel.

Welcome aboard.

**Comment by picklehari** [comment]
Hey, I had put in a pull request a few days back. I didn't quite get a invitation as collaborater and hence put it up as a pull request. And we'll be holding our first meetup next week, any procedures we need to do before that?

**Comment by hakutsuru** [comment]
Here is the link --
https://github.com/papers-we-love/kochi/invitations

You were invited as admin on `https://github.com/papers-we-love/kochi`. So you should be able to add Joel V Zach as a collaborator, if he has a GitHub account.

You and your chapter collaborators will normally approve/merge changes to your chapter. But if you would like comment/review/discussion, we are here to help.
