### ISSUE TITLE
Chapter Request: Stockholm

### ISSUE THREAD

**Issue by ostera** [papers-we-love/organizers#60]
> Have a chapter repository created within the Papers We Love organization: Open an issue on this repo requesting a chapter repo and telling us about yourself, who is helping you out, where we can find you online (twitter, etc) and where you're planning on starting the chapter. One of the Papers We Love administrators will get in touch with you and once everything is squared away will create the repo for your planned chapter. You will be added to a chapter-organizers team and given read / write access to the repo.

**Where**: Stockholm, Sweden

**Who**:
* Leandro Ostera (@ostera) – Researcher @SRC-technology, SWE @Doorling
* Fernando Via Canel (@xaviervia) – Researcher @SRC-technology, SWE @Klarna
* Iris Schaffer (@irisschaffer) – Researcher @SRC-technology, SWE @Spotify

**When**: Within this half of the year.

**Background**:
In the past SRC has sponsored events like #TheIlliterateProgrammer and #ReasonableCoding, and meetups like [ReasonSTHLM](https://meetup.com/ReasonSTHLM). Hosting and organizing Papers We Love aligns with our goals as an organization: https://github.com/SRC-technology/org

**Comment by hakutsuru** [comment]
@ostera, @xaviervia, @irisSchaffer -- Stockholm is setup - https://github.com/papers-we-love/stockholm

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
