### ISSUE TITLE
New Chapter: Nottingham, UK

### ISSUE THREAD

**Issue by fragmad** [papers-we-love/organizers#61]
Hi, 

**Where**: Nottingham, United Kingdom

**Who**:

- Will Ellwood (@fragmad) - Site Reliability Engineer, GoDaddy. My twitter handle is @fragmad 

**When**: Within the next three months, with an intention to announce in May as a bimonthly meetup.

**Background**: 

I am a member of the Nottingham based community hosted by Tech Nottingham (https://www.technottingham.com/) and would like the encourage more people within my geographic location to read more academic papers. :)

**Comment by hakutsuru** [comment]
@fragmad -- Nottingham is setup - https://github.com/papers-we-love/Nottingham

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by fragmad** [comment]
Thanks!

I have setup the basics of the repo and fully approve of the Code of Conduct.

**Comment by hakutsuru** [comment]
Thanks for the update. We will leave the issue open for a while, just in case there is follow up discussion.

If you have questions, that is not easy to glean from the docs, you should probably let us know. But you will probably find lots of useful information in slack and/or closed issues and pull requests.
