### ISSUE TITLE
Chapter Request: Buenos Aires

### ISSUE THREAD

**Issue by unbalancedparentheses** [papers-we-love/organizers#62]
> Have a chapter repository created within the Papers We Love organization: Open an issue on this repo requesting a chapter repo and telling us about yourself, who is helping you out, where we can find you online (twitter, etc) and where you're planning on starting the chapter. One of the Papers We Love administrators will get in touch with you and once everything is squared away will create the repo for your planned chapter. You will be added to a chapter-organizers team and given read / write access to the repo.

**Where**: Buenos Aires, Argentina

**Who**: Federico Carrone ([@unbalancedparen](https://twitter.com/unbalancedparen))

**When**: In the next two month. We will probably start at the end of August. I want to talk with @juanbono and @igaray to see with which paper we start.

Background:
I am the main organizer of a conference called [BuzzConf](https://buzzconf.org/), and coorganized a telecommunications conference called [Zruput](https://zruput.org/). I am one of the organizers of the [Rust Argentina meetup](https://www.meetup.com/Rust-Argentina/) and the [BeamBA meetup](https://www.meetup.com/BeamBA/). I work at [LambdaClass](https://github.com/lambdaclass/) and my blog is called [Not A Monad Tutorial](https://notamonadtutorial.com/).

I have read the code of conduct and I agree with it, specially with the "Be an adult, don't be a jerk" part.

**Comment by hakutsuru** [comment]
@unbalancedparentheses -- Buenos Aires is setup - https://github.com/papers-we-love/buenos-aires

Once you accept the invitation as repo collaborator, please update the Readme and Code of Conduct with your chapter's information. As an admin, you will be able to build a team to help manage the chapter.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so it is gratifying that you appreciate our Code of Conduct.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by unbalancedparentheses** [comment]
Thanks @hakutsuru. I am editing the README and the Code of Conduct. This week I hope to have everything translated to spanish.

**Comment by unbalancedparentheses** [comment]
Hi @hakutsuru where can I find the original assets (logo, etc) of papers we love? I might want to print a few t shirts, banner in a few months after we organize the first meeting. We already got more than 40 people in the telegram group!

**Comment by hakutsuru** [comment]
@DarrenN usually handles assets... Might take us a couple days to get back to you.
