### ISSUE TITLE
Chapter Request: Wroclaw/Poland

### ISSUE THREAD

**Issue by EncodePanda** [papers-we-love/organizers#63]
Hi, 

my name is Pawel Szulc (twitter: @rabbitonweb) and I live in Wroclaw/Poland. Beside hacking day and night I enjoy reading papers and organize local events. I love the idea behind Papers We Love (I've been benefiting from it over the last couple of years). I would like now give back to the community and run the local Wroclaw (Poland) chapter.

**Comment by hakutsuru** [comment]
@rabbitonweb -- Wroclaw is setup - https://github.com/papers-we-love/wroclaw

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. As an admin, you will be able to add other organizers to help manage the chapter repo.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by rabbitonweb** [comment]
This is awesome, thx!
