### ISSUE TITLE
Chapter Request: Los Angeles

### ISSUE THREAD

**Issue by emkay** [papers-we-love/organizers#64]
Hi all! 🌊 

I'm Michael Matuzak and have picked up organizing the Los Angeles, CA chapter. You can find me at [@mmatuzak](https://twitter.com/mmatuzak) on twitter. As of this moment I do not have anyone helping out, but I will be looking for some folks to come on board as co-organizers.

Cheers

**Comment by hakutsuru** [comment]
@emkay -- Los Angeles is setup - https://github.com/papers-we-love/los-angeles

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. When you have co-organizers, you can grant them access to the chapter repo.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
