### ISSUE TITLE
Chapter Request: Beijing

### ISSUE THREAD

**Issue by jiangplus** [papers-we-love/organizers#65]
Hi Papers-We-Love Folks!

I am Jiang(@jiangplus) in Beijing. I am a senior backend engineer for Xtalpi, a machine learning startup. I would like to organize the Papers We Love Beijing Chapter. 

We have internal paper study group for topics on machine learning, distributed system and cloud native architecture. We would like to knowledge to more people and expand PWL to Chinese communities.

You can also find me on twitter [@jiangplus](https://twitter.com/jiangplus)

**Comment by hakutsuru** [comment]
Will handle this over the next few days.

**Comment by jiangplus** [comment]
Thanks. That would be great. @hakutsuru

**Comment by hakutsuru** [comment]
@jiangplus -- Beijing is setup - https://github.com/papers-we-love/beijing

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. You will be a project admin, so you are free to add other collaborators to assist you.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
