### ISSUE TITLE
Chapter Request: Milano, Italy

### ISSUE THREAD

**Issue by evacchi** [papers-we-love/organizers#66]
Hey there!

This is Edoardo Vacchi [@evacchi](https://twitter.com/evacchi). I am trying to organize a local PWL meetup with a bunch of friends. I have an academic background (PhD in programming language research) and I am currently employed at Red Hat. The Milano tech scene is quite active and there are many meetups, but nothing like Papers We Love. We believe times are mature to attract R&D departments, startups, universities and, of course, interested individuals.

We plan to organize our first meeting on the second half of October.

I have read the code of conduct and I agree with it.

**Comment by hakutsuru** [comment]
@evacchi -- Milano is setup - https://github.com/papers-we-love/milano

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. You will be an admin of the project, so you should invite other chapter collaborators when appropriate.

Thanks for reading the Code of Conduct, we hope every new chapter will embrace our mission to foster open and accepting communities -- let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by evacchi** [comment]
Thank you!!
