### ISSUE TITLE
Chapter Request: Indore, India

### ISSUE THREAD

**Issue by pallav-systango** [papers-we-love/organizers#67]
Hello Paper We Love Folks!

I am Pallav Boonlia in Indore, India. I am Director of engineering at Systango , a Mobile development scale-up.  I would like to organise the Papers We Love Indore Chapter. 

Indore has a growing tech crowd as well as several well-respected academic establishments (IIM Indore, IIT Indore etc.) but nothing like Papers we love . I would like there to be a Papers We Love chapter here. We have a local meet up group which meets on for topics on IoT , Cloud Computing , DevOps and api design.

We plan to organise our meeting in first half of November. You can find me on linkedIn [Pallav Boonlia](https://www.linkedin.com/in/pallav-boonlia/)

Location: Coffee shops (I know one that has hosted meetups).

I have read code of conduct and I agree with it.

**Comment by hakutsuru** [comment]
@pallav-systango -- Indore is setup - https://github.com/papers-we-love/indore

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information. You will be an admin for the project, so you can invite other chapter collaborators over time.

Thanks for reading the Code of Conduct, we hope every new chapter will embrace our mission to foster open and accepting communities -- let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by pallav-systango** [comment]
@hakutsuru - Thankyou

**Comment by pallav-systango** [comment]
@hakutsuru - I updated Code of Conduct and Readme and created a PR for https://github.com/papers-we-love/indore/pulls however i dont have merge rights. Can you merge the PR and add me as collaborator to Repo?

**Comment by hakutsuru** [comment]
> dont have merge rights

You have an invitation to the repo as an admin. Please check your email, and/or GitHub. I would be happy to review and merge for you, but we should resolve repo access (and you being able to merge is a good test). Thanks.

![indore-collab](https://user-images.githubusercontent.com/998012/64560736-0f8b3280-d317-11e9-8d8c-3a6bf8c3bcb1.png)
