### ISSUE TITLE
Chapter Request: Cork, Ireland

### ISSUE THREAD

**Issue by paulodhran** [papers-we-love/organizers#69]

**Comment by hakutsuru** [comment]
@heypaulmcgrath -- Cork is setup - https://github.com/papers-we-love/cork

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. You will be the project admin, and are encouraged to add other chapter organizers as collaborators in the future.

With abuse and harassment recently in the news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by heypaulmcgrath** [comment]
Fantastic! Thank you, @hakutsuru.
