### ISSUE TITLE
Chapter repo request.

### ISSUE THREAD

**Issue by tetek** [papers-we-love/organizers#7]
I would like to open a chapter in Warsaw, Poland. I'm now pursuing my Master's degree at University of Warsaw. You can find me on twitter: http://twitter.com/wmandrysz, or my website: http://binarka.pl/wojtek.
Let me cite Richard Feynman, because it's describe my attitude perfectly "The prize is the pleasure of finding a thing out, the kick in the discovery, the observation that other people use it — those are the real things.". I will find co-organizers at my university, and I already have contacts with couple companies that could help with space.

**Comment by DarrenN** [comment]
@tetek - your repo is up at https://github.com/papers-we-love/warsaw

You should have received an invite to join the **team-organizers** group which will give you access to the repo.

Please update the README and Code of Conduct within the repo.

Thanks!

- D
