### ISSUE TITLE
Chapter Request: Joinville, Brazil

### ISSUE THREAD

**Issue by alfakini** [papers-we-love/organizers#70]
Hi! 

# Where

[Joinville/SC, Brazil](https://goo.gl/maps/RyxxQhjfujgBE5WD8)

# Who

Alan Rafael Fachini, Software Engineer and founder of [Magrathea Labs](https://www.magrathealabs.com/) and board member of [Fab Lab Joinville](http://www.fablabjoinville.com.br/), [@alfakini on Twitter](https://twitter.com/alfakini) and [@alfakini on GitHub](https://github.com/alfakini/).

I have been wanting for a long time to start a Papers We Love chapter in Joinville, and next year I will have time to lead the beginning of the chapter. The meetups will be hosted at Santa Catarina State University with help of students from the Computer Science Department.

# When

Starting at February, with the intention to host as a monthly meetup.

# Background

I'm member of the Brazilian Computer Science Association and helped start some tech communities in the city in the past years: [Python Joinville](http://python.joinville.br/), [Ruby Joinville](http://ruby.joinville.br/), [Data Science Joinville](http://dados.joinville.br/). I have experience organizing communities and events.

I also have interest in academic papers, and would love to encourage more engineers in my area to share and discuss new and emerging ideas.

**Comment by hakutsuru** [comment]
@alfakini -- Joinville is setup - https://github.com/papers-we-love/joinville

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
