### ISSUE TITLE
Chapter Request: Kansas City, MO USA

### ISSUE THREAD

**Issue by ejmg** [papers-we-love/organizers#71]
hi there, this is the same `elias`/`ejmg` from the PWL Slack.

# where

Kansas City, Missouri USA

# who

i, Elias Julian Marko Garcia, am the main organizer and can be reached best by email at either elias.jm.garcia AT gmail.com *or* elias.jm.garcia AT pressmail.ch. you can also find some alternative methods to reach me on [my website](https://ageof.info/contact). caveat, i lost access to my twitter :grimacing:.

my co-organizer is Hedon (@HDEHacks) and is available via jdmaravelias AT gmail.com.

# when

PWL KC has *successfully met already 4 times*(!) over the past consecutive months on the third Thursday at the KC Public Library's central branch location in downtown, KC, MO. we plan on staying here for the foreseeable future thanks to the affordability and availability of the rooms for groups of sizes 6-15.

# background

i am a senior at UMKC and am due to graduate in May of 2020. i've been a big fan of PLT, the details/ideas that go behind systems and language design, and various other topics that have always made starting a PWL chapter attractive to me. I don't have any immediate plans to leave the KC area in the immediate future, but luckily....

Hedon is a local engineer at $COMPANY in KC, MO and is in a similar boat with respect to personal interests. Hedon is also on track to stay in the area for some time to come, meaning that PWL KC has two organizers who will be able to coordinate the group for the coming 6 months and at least one organizer who will be able to coordinate the group for at least 1 year.

KC has a great tech community, we're just (unfortunately) spread out across the metro area due to suburban sprawl. PWL KC is trying to fix that in our own little way while having a good time networking and learning :slightly_smiling_face:

**Comment by hakutsuru** [comment]
@ejmg & @HDEHacks -- Kansas City is setup - https://github.com/papers-we-love/kansas-city

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved.

Everyone is encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

(Thanks for reaching out to us there, @ejmg.)

Welcome aboard.

**Comment by ejmg** [comment]
Thank you so much for the opportunity! To many more PWL KC meetings :slightly_smiling_face:
