### ISSUE TITLE
Chapter Request: Dublin, Ireland

### ISSUE THREAD

**Issue by davoli** [papers-we-love/organizers#72]
Hi all, 

my name is Antonio and I am a Production Engineer at Facebook, where I work on machine learning solutions for systems. Together with [Giacomo Bagnoli ](https://github.com/gbagnoli) we used to run a papers reading group internally at the Facebook Dublin office, and we would like to start a chapter of PLW here in Dublin.

Thanks!

**Comment by hakutsuru** [comment]
@davoli & @gbagnoli -- Dublin is setup - https://github.com/papers-we-love/dublin

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

I may visit Dublin in late March, so let me know if schedule any events then. Thanks!

Welcome aboard.

**Comment by davoli** [comment]
Hi Sean, 

Thanks for the follow up, i'll address the change for the Readme and Code of Conduct shortly. I was targeting beginning of March for the first event, but I will keep you posted. In any case you should stop by Dublin drop me a message!
