### ISSUE TITLE
Chapter Request: Silicon Valley

### ISSUE THREAD

**Issue by frankieliu** [papers-we-love/organizers#73]
# Where
Silicon Valley, South Bay, US

# Who
Frankie Y Liu, Software Engineer SF Bay area. 
[link to contact info](https://www.frankliu.org/hugo)

# What
We have been meeting since November of 2019, every week on Saturdays and Sundays.
[meetup link](https://www.meetup.com/SF-BayArea-Distributed-Systems-Reading-Group/events/hlmrnrybcdblb/)

Please let me know what needs to be done in order to automatically pull events from meetup.
Currently we are reading through Craq paper and Aurora paper.  We spent some time on Kleppmann, Raft, Zookeeper recently.  On Sundays, we implement some of things we learned from the papers.

# When
Saturdays 9-12am PST and Sundays 2-5pm PST

# Background
I have been a hardware engineer for most of my life.  Programming has always been a hobby since childhood.

**Comment by deltamualpha** [comment]
Hi Frankie!

A couple of questions:

1. The meetup link posted is for "Scalable Systems Study Group", and appears to be more of a reading-and-implementation group. Papers We Love groups have been more focused on presentations from speakers about papers and then questions afterward, although some groups are more group-discussion oriented. We do require that if you're running a Papers We Love local group that it be purely focused on that structure and use the PWL name; we are not an umbrella organization of CS reading groups.
2. Have you been in contact with the organizers of the San Francisco PWL group? https://paperswelove.org/chapter/sanfrancisco/ We're worried that having two groups in such close proximity would be detrimental to attendance or speaker availability for both of them.
3. Meeting twice a week for multiple hours seem like a very time-intensive commitment for members. Again, nothing wrong with that, but it seems outside of the standard PWL model.

**Comment by frankieliu** [comment]
Hi David,

Thanks for the questions.  While the Sunday meetup is definitely more of an
implementation group, the Saturday group is purely a reading group.  I am
completely ok with having speakers, but it is hard to get them, so we are
by default more group-discussion oriented.  I have read the code of conduct
and I am completely in favor of it.  As to structure, I don't think there
is one right structure, it really depends on the members and what works for
them.  I am always open to suggestions.  As for the PWL name, let me know
what that would entail -- I am open to suggestions.

As to the SF group, it is precisely because it is hard to attend these
meetings that we have a group in the South Bay, perhaps most people outside
of SF bay area don't realize it is quite a commute to go from San Jose to
San Francisco on a weekday night, thus making it detrimental to the
attendance from South Bay people.  Since we are not strong on speaker
invitation, I don't think we conflict with the SF group.  But I will
definitely coordinate with the SF group if that becomes a modus operandi
for us.

Re. meeting every week, we don't believe that reading is a one time event,
often we read the same paper for couple of weeks to really ingest its
contents, and we bring back old papers that have gathered dust.  I am not
sure what is the standard PWL model.

I really appreciate your questions, and hope that I was able to answer some
of your concerns.  I am more than happy to discuss live if that helps
(650)269-3063.

Have a great day!

-frankie

**Comment by frankieliu** [comment]
Dear all, I just reread the community main page, and I think we are definitely doing all the three main things listed there:  reading, discussing, and learning more about academic computer science papers.  One might even argue that implementation is one way to learn.  But again the Saturday meeting does very much conform to all the guidelines.   Hope this helps.  -f

Copied from repo:

Papers We Love (PWL) is a community built around reading, discussing and learning more about academic computer science papers. This repository serves as a directory of some of the best papers the community can find, bringing together documents scattered across the web. You can also visit the Papers We Love site for more info.

Due to licenses we cannot always host the papers themselves (when we do, you will see a scroll emoji next to its title in the directory README) but we can provide links to their locations.

If you enjoy the papers, perhaps stop by a local chapter meetup and join in on the vibrant discussions around them. You can also discuss PWL events, the content in this repository, and/or anything related to PWL on our Slack, after signing-up to join it, or on our #paperswelove IRC channel on freenode.
