### ISSUE TITLE
Chapter request: Poznan/Poland

### ISSUE THREAD

**Issue by mikulskibartosz** [papers-we-love/organizers#74]
Hi,
I would like to run a local "Papers We Love" chapter in Poznan, Poland.

Currently, I am organizing local Software Craft Group in Poznan. In the past, I also organized meetups of Poznan Scala User Group and a School of A.I. chapter.

You can find me online at https://mikulskibartosz.name and on Twitter: @mikulskibartosz

**Comment by hakutsuru** [comment]
@mikulskibartosz -- Poznan is setup - https://github.com/papers-we-love/poznan

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment often in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
