### ISSUE TITLE
Chapter request: Guatemala

### ISSUE THREAD

**Issue by montjoile** [papers-we-love/organizers#75]
Hello everyone! 👋🏻

**Where:**
Guatemala City, Guatemala

**Who:**
Sara Iris Garcia (Twitter> [@montjoile](https://twitter.com/montjoile))

**When:** 
By the end of March 2020, the set up is intended to be a monthly Meetup.

**Background:**
I am a member of the tech community in Guatemala City, and I regularly speak on topics related to Python and data. I am interested in open source, and accessibility in research. I would like to start a PWL chapter in Guatemala to encourage people, especially young researchers and women to science.  You can find me on [Linkedin ](https://www.linkedin.com/in/sarairisgarcia/)or have a look at my [blog](http://www.sara-codes.com/).

I have read the Code of conduct and I accept it.

**Comment by hakutsuru** [comment]
@montjoile -- Guatemala City is setup - https://github.com/papers-we-love/guatemala-city

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. As admin for the chapter, you can add other collaborators later.

Thanks for reading the Code of Conduct. After your chapter holds its first meeting, please follow-up to add Guatemala City to the <https://paperswelove.org> site.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
