### ISSUE TITLE
Chapter request: Dallas, TX

### ISSUE THREAD

**Issue by prochafilho** [papers-we-love/organizers#78]
# Where
Dallas, TX, US

# Who
[Paulo Da Rocha](https://www.twitter.com/paulinhorocha)
[Henrique Baleroni](https://www.github.com/hbaleroni)

# Background
We are software developers based in Dallas, TX. Paulo is one of the founders and helped run the monthly meetings of the [Dallas chapter](https://prochafilho.github.io/dallas/) for [Nodeschool](https://www.nodeschool.io), an open-source global organization that uses workshops that teach web software skills. 
We would like to help disseminate knowledge by host monthly meetings to discuss papers found on PWL.

**Comment by hakutsuru** [comment]
@prochafilho, @hbaleroni -- Dallas is setup - https://github.com/papers-we-love/dallas

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment consistently in the (North American) news, we hope every chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by prochafilho** [comment]
Thank you! I am planning on organizing virtual meetings first; then, move to in-person meetups.

**Comment by hakutsuru** [comment]
> organizing virtual meetings

Seattle has been having regular meetings (using crowdcast and zoom). NYC is holding irregular meetings (using twitch). Good luck!
