### ISSUE TITLE
Chapter Request: Tel Aviv, Israel

### ISSUE THREAD

**Issue by AdamGS** [papers-we-love/organizers#79]
**Where:**
Tel Aviv, Israel

**Who:**
Me (Adam Gutglick, @adamm_gs on twitter), and Omri Kaduri (@OmriKaduri here on github)

**When:**
Hopefuly by January, I'm to run a meetup every month or two, starting remotly and hopefully we can all get together soon.

**Background:**
I'm a software engineer developing data pipelines, with an interest in "academic" knowledge, espicailly when working in a field that is mostly based on systems developed straight from various papers. Omri is running a R&D group dealing with some challenges in the computer vision space, while pursuing his MSc and soon PhD.

I have read the Code of conduct and I accept it.

**Comment by hakutsuru** [comment]
@AdamGS, @OmriKaduri -- Tel Aviv is setup - https://github.com/papers-we-love/tel-aviv

Once you accept the invitation as collaborators, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- thanks for acknowledging the Code of Conduct.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
