### ISSUE TITLE
Chapter Request: Timisoara, Romania

### ISSUE THREAD

**Issue by zalmanu** [papers-we-love/organizers#8]
_Where_: Timișoara, Romania
_Who_:

- Emanuel Danci, @zalmanu, Software Engineer at [Atigeo](http://atigeo.com/)
- Vlad Temian, @vtemian, Software Engineer at [Presslabs](https://www.presslabs.com/)

**Comment by zalmanu** [comment]
Hi @DarrenN, 

Anything new on this one? Thanks.

**Comment by DarrenN** [comment]
https://github.com/papers-we-love/timisoara

Please update the README and Code of Conduct.

Thanks!
