### ISSUE TITLE
Chapter Request: Lancaster, Pennsylvania

### ISSUE THREAD

**Issue by alejandrogomez314** [papers-we-love/organizers#80]
Where:
Lancaster, Pennsylvania, United States

Who:
Me - Alejandro Gomez. Username is @agomez314 on twitter and github. My personal blog is https://alejandrogomez.blog. So far, it's only me but I hope to meet others and grow the community.

When:
Will start in March and will be holding meetings once a month

Background:
I'm a software engineer who loves learning about the art and science of computing and wish to share that with others. I currently work at a financial services firm and recently completed my Masters in Software Engineering from Villanova University. 

I have read the Code of conduct and I accept it.

**Comment by hakutsuru** [comment]
@agomez314 -- Lancaster is setup - https://github.com/papers-we-love/lancaster

Once you accept the invitation as admin, please update the Readme and Code of Conduct with your chapter's information.

With abuse and harassment persistently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- thanks for accepting the Code of Conduct, let us know any thoughts for improving our docs.

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.

**Comment by agomez314** [comment]
Thanks! Looking forward to building up the community through the shared love we have for computing. Cheers!
