### ISSUE TITLE
Chapter Request: Bangladesh [Dhaka]

### ISSUE THREAD

**Issue by annajiat** [papers-we-love/organizers#81]
Where:
Bangladesh, Asia

Who:
Me - Annajiat Alim Rasel. Username is @annajiat on Twitter and GitHub. Linkedin is [here](https://www.linkedin.com/in/annajiat/). I hope to meet others and grow the community.

When:
Will start in April/May and will try holding meetings once a month

Background:
I'm a lecturer of CS who loves learning about CS and try disseminate to others. Both teaching and research require going through papers. Our region could benefit from the initiative.

I have read the Code of conduct and I accept it.

I have already joined the slack.

**Comment by hakutsuru** [comment]
@annajiat Would these meetings be held at or near BRAC University?

PWL Chapters are usually named for cities. Bangladesh is too large an area to be a good chapter name. Would Dhaka be the most appropriate location for your chapter?

**Comment by annajiat** [comment]
@hakutsuru 
Meetings would be held online mostly and occasionally at Brac University initially.

Yes, Dhaka could be a suitable alternative.

**Comment by hakutsuru** [comment]
@annajiat -- Dhaka is setup - https://github.com/papers-we-love/dhaka

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. You may invite other chapter organizers to collaborate on the repo.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities. Thanks for reading the Code of Conduct. Let us know if it can be improved (or made more culturally aware).

If you have any questions, reach out on slack.

Welcome aboard.
