### ISSUE TITLE
Chapter Request: Windhoek ,Namibia

### ISSUE THREAD

**Issue by nnashandi** [papers-we-love/organizers#82]
Hello! 

Where:
Windhoek ,Namibia

Who:
Ndinelago Nashandi , Computer Science Lecturer @ Namibia University of Science and Technology . I am being help by Prof Jose Quenum a Computer Science Associate Professor at Namibia University of Science and Technology as well. (@nashandin and @menuc on Twitter)

When: We will start in September and we will be holding meeting every month 

Background:
We are busy creating a Data science Community within the university and we have interest in academic 
academic papers, and would love to encourage Data science Community members to share and discuss new and emerging ideas in Data Science. I am looking forward to pursue a PhD in Big Data Analytics.

**Comment by hakutsuru** [comment]
@nnashandi -- Windhoek is setup - https://github.com/papers-we-love/windhoek

Once you accept the invitation as collaborator, please update the Readme and Code of Conduct with your chapter's information. Add other organizers as appropriate.

With abuse and harassment recently in the (North American) news, we hope every new chapter will embrace our mission to foster open and accepting communities -- so please read the Code of Conduct, and let us know if it can be improved (or made more culturally aware).

You are encouraged to join our slack -- http://papersweloveslack.herokuapp.com/

Welcome aboard.
