### ISSUE TITLE
Chapter Request: Portland, Oregon, USA

### ISSUE THREAD

**Issue by jdavisp3** [papers-we-love/organizers#84]
Where:
I'm interested in starting a Papers We Love chapter in Portland, OR, USA.

Who:
Me (Dave Peticolas (https://krondo.com, https://www.linkedin.com/in/dave-peticolas-0bb45b1/) in collaboration with Chris Mason (https://www.linkedin.com/in/christopher-mason-510a291/) @masoncj

When:
Soon, we are getting a space secured and reaching out to more Portland contacts.

Background:
I've worked in software for two decades and have a Masters in Computer Science. I'd like to encourage more reading of the literature and discussion of where the field is going. Chris is an engineering leader with an academic background and many local connections.

I've read and I accept the Code of Conduct.

**Comment by jdavisp3** [comment]
Update: we have a space and are starting to gather more interest.

**Comment by hakutsuru** [comment]
@jdavisp3

Good to hear you are making progress. There was a Portland Chapter started in 2016, but it appears inactive. We usually have organizers work together on transition.

But I will discuss this situation with the PWL team here, and try to move this forward. Thanks for your patience.

**Comment by jdavisp3** [comment]
Thanks 👍🙂

**Comment by hakutsuru** [comment]
@carllerche @fitzgen

There is interest in starting a new Portland Chapter. Seems the last meeting was in 2017, per twitter.

Would it be okay to transfer the repo and twitter accounts to a new team?

Hope this ping finds you well, after the past few difficult years, we are seeing new chapters form and in-person events start again... And it feels awkward. Thanks for any attention you can provide.

****

@jdavisp3

The old meetup page is defunct, but there was a twitter handle `pwlpdx` for Portland that could be useful.

The Portland repo is here:
https://github.com/papers-we-love/portland

Perhaps it would nice if the chapter history was acknowledged in an archive page.

Before transferring the repo, we like the old team to acknowledge-approve the action. The previous organizers would/should be able to do this, but it has been some time, so I would handle this if they are unavailable.

If you use twitter, or know any of the previous organizers, feel welcome to reach out and see if they could turn over the twitter account -- or would be willing to help in any way.

**Comment by jdavisp3** [comment]
Thanks @hakutsuru ! I searched for an existing chapter in Meetup but I clearly missed this one. @carllerche and @fitzgen if you are interested in starting back up there's some new interest in this activity. I'm not on Twitter but we can probably find some folks who are.

**Comment by hakutsuru** [comment]
I anticipate PWL core team will have meeting this week. Our primary focus is setting up PWLConf this year, but I will try to discuss chapter issues, too.

Thus, I hope to either create a different repo, or transfer the existing repo, later this week.

****

Sent email to previous organizers, as copied below...

From: Sean Broderick <sean@paperswelove.org>
Subject: PWL PDX Chapter
Date: May 8, 2022 at 9:12:03 PM EDT
To: Carl Lerche <me@carllerche.com>, Nick Fitzgerald <fitzgen@gmail.com>
Cc: Dave Peticolas <dave@krondo.com>

Carl Lerche, Nick Fitzgerald:

Sorry to ping you out of the blue.

Dave Peticolas and Chris Mason wish to restart a chapter in Portland. Please see issue...
https://github.com/papers-we-love/organizers/issues/84

If you could participate in this discussion, or contact the new team privately to chat about this, that would be appreciated. Thanks.

Sean Broderick
Organizer, PWL NYC

**Comment by hakutsuru** [comment]
PWL Core has discussed this, and I have been tasked with transferring the existing repo to the new team in the next several days.

(Without any response from the old team, legacy related resources like twitter/meetup accounts should be abandoned, and new resources with different naming created as desired.)

**Comment by jdavisp3** [comment]
Thank you @hakutsuru !

**Comment by carllerche** [comment]
I'm happy to hand it off, sorry for the delay.

**Comment by jdavisp3** [comment]
Thanks @hakutsuru !  I am on that Slack as Dave Peticolas.

**Comment by hakutsuru** [comment]
@carllerche

Good to hear from you! I do not think we have meet, but I suspect you know Zeeshan.

> What do you need from me?

Thanks for entering the discussion.

Your acknowledgement of the transfer is helpful, and anything else may be impractical.

Here are ideas on what could be useful...

- Twitter: Transferring the old account would be great.

- Mailing List: While the information would be years old, if you have a mailing list for the Portland Chapter, you could give it to the new team.

- Meetup: This resource may be less commonly used... If the new team was considering Meetup, and that account contact could be reset, it may make things simpler.

**Comment by carllerche** [comment]
I guess the best way to transfer the twitter account would be to change the email address. Is dave@krondo.com a good one?

**Comment by jdavisp3** [comment]
@carllerche I don't actually have a Twitter account but I'll see if Chris might want to take it.

I already created a new Meetup Group.

**Comment by jdavisp3** [comment]
We've got our Meetup site and the first event scheduled:

https://www.meetup.com/papers-we-love-pdx/events/286209448/

Anything else I need to do? Otherwise I can close this ticket.

**Comment by DarrenN** [comment]
Pro-tip: Post your meetups in the Slack general channel and we're happy to amplify from the main Twitter account when we can.

**Comment by jdavisp3** [comment]
> Pro-tip: Post your meetups in the Slack general channel and we're happy to amplify from the main Twitter account when we can.

Done! And thank you @DarrenN

**Comment by hakutsuru** [comment]
@jdavisp3 Appreciate the follow-up. Everything looks good. I am closing the ticket for you, because you should be doing holiday weekend stuff :)
