### ISSUE TITLE
Chapter Request: Sydney, Australia

### ISSUE THREAD

**Issue by rjerrems** [papers-we-love/organizers#90]
Hi There,

We are big fans of papers we love and are requesting to start a chapter in Sydney, Australia.

The initial group of organisers are all Googlers, but we would be happy to include others once the community gets going.

@meetdestiny @jaqx0r will be fellow organisers.

Cheers,
Rohan

**Comment by meetdestiny** [comment]
My linkedin page :  https://www.linkedin.com/in/akhilesh-singh-ml/

**Comment by DarrenN** [comment]
@rjerrems so, a Sydney Chapter was setup in 2018 -> https://github.com/papers-we-love/sydney

It was requested by https://github.com/OzanGunaydin

Doesn't look like there was any follow through on setting up the chapter, happy to put the three of you in charge and reboot the process.

**Comment by rjerrems** [comment]
Oh right, I didn't see that - AFAICT the previous requester is not longer in Australia, so probably makes sense for the three of us to take charge and reboot. I have joined the discord and will let the others know!

**Comment by DarrenN** [comment]
@rjerrems @meetdestiny @jaqx0r  - you should all have invites from GitHub to take over this repo and use it for organizing

**Comment by rjerrems** [comment]
Ok great - thanks @DarrenN
